twreporter/twreporter-react

- src/App/App.jsx
- src/HTML/HTML.jsx
- src/index.js
要使用 HashLocation 以及少了 RouteHandler 。
> Make react-router works

- server/views/index.ejs
- src/store/configureStore.js
> load css and change log level

- package.json
- server/views/index.ejs
- src/actions/articles.js
- src/components/Features.css
- src/components/FeaturesItem.css
- src/components/FeaturesItem.js
- src/components/Parallex.jsx
- webpack.config.js
Use Parallex component from http://codepen.io/radociech/pen/LVpVob
@hcchien
> Add Parallex for image of FeaturesItem.js

- server/views/index.ejs
- src/components/FeaturesItem.js
- src/containers/Home.js
@hcchien 
Basically, we have the parallax effect.
However, there is one thing not done.
We can discuss it tmr.
> Parallax by ScrollMagic

- src/components/FeaturesItem.js
> show the footer and make the parallax more user friendly

- src/components/FeaturesItem.js
> handle browser resizing

- src/components/FeaturesItem.js
> retain scrollScene and scrollController, not really set them as null

- src/components/FeaturesItem.css
- src/components/FeaturesItem.js
- src/components/Footer.js
1. following images shows too early. 
2. the image shakes a little bit when position fixed
@hcchien
> fix parallax bug. 

- src/components/FeaturesItem.css
- src/components/FeaturesItem.js
> fix move style to css

- src/components/Daily.css
- src/components/Daily.js
- src/components/TopNews.css
> style update

- src/components/FeaturesItem.js
> only resize and attach parallax for desktop

- src/components/TopNews.css
- src/components/TopNews.js
The css spacing is weird, will solve this problem later.
> mobile topnews style

- src/components/FeaturesItem.css
- src/components/FeaturesItem.js
> modify pushlish date style

- src/components/Footer.css
- src/components/Footer.js
> add footer.js and footer.css

- src/components/Footer.css
- src/components/Footer.js
> desktop footer

- src/components/NavBar.js
> replace logo on NavBar

- src/components/Features.css
> remove the empty block below the feature items

- src/components/Footer.css
- src/components/Footer.js
> text vertical align with image

- src/components/Daily.js
- src/components/Features.js
- src/components/FeaturesItem.js
- src/components/TopNews.js
- src/middleware/api.js
1. Parse api json response to camel case
2. Render featureItem only if firstImage or previewImage exists
@hcchien
> code change

- src/components/Features.js
- src/components/TopNews.js
> error handling

- src/lib/date-transformer.js
> add lib/date-transformer

- src/components/TopNews.js
> change slideshow settings

- package.json
> downgrade react-slick

- package.json
> fix react-slick version

- package.json
- server/server.js
- src/components/Daily.js
- src/components/Features.js
- src/components/TopNews.js
- src/containers/Home.js
- src/lib/image-composer.js
- src/reducers/device.js
- src/reducers/index.js
> add device detect and render appopriate image for different device

- src/components/FeaturesItem.css
> show right border

- src/components/TopNews.css
> let image full with screen on mobile

- src/components/Features.css
- src/components/Features.js
> css change

- src/components/TopNews.js
> freeze the autoplay after clicking

- src/components/TopNews.js
> hack for stopping autoplay

- src/components/Daily.js
> show whole image

- src/components/FeaturesItem.css
- src/components/FeaturesItem.js
> add subtitle

- src/components/TopNews.css
> change media query width

- src/components/TopNews.js
> enable carousel arrows on mobile

- .editorconfig
- .eslintrc
- package.json
- server/index.js
- server/mock_api.js
- server/server.js
@nickhsine  #60 
I am not sure this style preset works for everyone, but If you have any concern please just let me know.
Let me try the style on `/server` first and if the rules works, I will fix other files gradually.
> apply eslint and editorconfig

- package.json
> Force use histroy v1.13.x

- src/components/TopNews.js
> remove hack for stopping carousel after clicking

- src/components/Footer.js
> click logo to back to home page

- src/lib/image-composer.js
> use width 1200 image for desktop and mobile

- server/views/index.ejs
Merge this after https://github.com/twreporter/infographics/pull/4 for #59
> RSS 2.0 link

- src/lib/image-composer.js
> detect gif as image

- src/components/FeaturesItem.css
make it vertical center aligned.
> adjust style of featurebox category text

- src/components/Category.css
- src/components/Category.js
- src/components/FeaturesItem.css
- src/components/FeaturesItem.js
- src/components/TopNews.css
- src/components/TopNews.js
I also made it responsive by adopting this svg background and used in topnews and featurebox with different size.
Maybe you can remove the `hexagon.png` after use this component everywhere.
> add Category component

- src/components/Features.js
- src/components/More.css
- src/components/More.js
- src/containers/Home.js
- src/reducers/articles.js
Because the data structure of api responses are different (fetching from ```API_HOST/tags``` and ```API_HOST/article```),
there are two business logic in reducer(```LOADED_MULTI_TAGGED_ARTICLES_SUCCESS```,
```LOADED_ARTICLES_SUCCESS```) to handle them.
@hcchien 
@kaddopur
> Load more functionality for feature items

- src/components/Daily.js
- src/components/Features.js
- src/components/Tags.js
- src/components/TopNews.js
- src/lib/image-composer.js
> choose image to show on client side

- src/components/Tags.css
- src/components/Tags.js
- src/containers/Category.js
> add load more for Category container

- src/components/More.css
> style change

- package.json
- src/components/FeaturesItem.js
- src/components/NavBar.css
- src/components/NavBar.js
- src/containers/Category.js
- src/store/configureStore.js
> make navigation bar work

- src/components/NavBar.css
- src/components/NavBar.js
- src/components/NavBurg.css
- src/components/Tags.css
- src/components/Tags.js
> nickhsine	make nav burger work for mobile

- browsersync-server.js
- package.json
- server/index.js
- server/server.js
and use server.js as middleware directly with browserSync.
> remove nodemon

- browsersync-server.js
- package.json
- webpack.config.js
and use react-transform-hmr.
Beware of that now there is no server-side reload offered by nodemon.
> add webpack-hot-middleware

- src/containers/Category.js
> add componentWillMount to show category items

- src/components/NavBar.js
> make logo link back to home page

- src/components/Daily.js
- src/components/FeaturesItem.js
- src/components/Footer.js
- src/components/Tags.js
- src/components/TopNews.js
- src/lib/image-composer.js
to fix this issue https://github.com/twreporter/twreporter-react/issues/109
However, using relative link will cause some inconvenience. 
Because article pages suffixed by ```/a/{slug}``` are hosted on other servers, we may not see those pages on our dev server.
@hcchien @kaddopur
> use relative link

- .babelrc
- package.json
> add presets stage-0 for es7

- src/components/DesktopNavBar.js
- src/components/MobileNavBar.js
- src/components/NavBar.css
- src/components/TopNews.css
- src/containers/Category.js
- src/containers/Home.js
- src/containers/Photography.js
mobile version not implement yet because of lacking of spec
> Navigation tuning according to spec

- src/actions/articles.js
- src/components/TopNews.js
- src/containers/Home.js
- src/containers/Photography.js
> Dev for preflight

- server/views/index.ejs
- src/components/Daily.js
- src/components/DesktopNavBar.js
- src/components/NavBar.css
- src/components/NavBar.js
- update title & description
- setting h1 html tags
H1 headings help indicate the important topics of your page to search engines.
> Google SEO

- server/views/index.ejs
@hcchien 
https://cse.google.com/cse/setup/basic?cx=008042460408727773288:mvn-lce5wvo
also modify the site config.
> use another search engine

- src/components/DesktopNavBar.js
- src/routes/index.js
> only index page has search box and change background color for /photography

- src/components/DesktopNavBar.js
> use style to hide search box

- src/components/MobileNavBar.js
> change background color for mobile navbar

- src/components/MobileNavBar.js
- src/components/NavBar.css
> make logo fit in 414px width(below) device

- package.json
- server/index.js
> fix bug and add log for forever

- src/components/DesktopNavBar.js
- src/components/MobileNavBar.js
- src/conf/category-tag-mapping-table.js
> replace category/media by category/intl

- src/components/TopNews.js
> show category name on TopNews

- src/components/MobileNavBar.js
> [hotfix] temporary solution for hiding menu burger on mobile

- server/views/index.ejs
> html add lang attribute

- src/components/DesktopNavBar.js
- src/components/MobileNavBar.js
- src/lib/constants.js
- src/lib/image-composer.js
> code refactor

- src/components/DesktopNavBar.js
- src/components/MobileNavBar.js
- src/components/NavBar.css
- src/components/NavBar.js
- src/conf/category-tag-mapping-table.js
- src/lib/constants.js
- src/reducers/device.js
1. remove burger menu on Mobile
2. Style NavBar for desktop and tablet
@hcchien
> Code change for NavBar

- package.json
- server/views/index.ejs
- src/components/FeaturesItem.js
- webpack.config.js
> build ScrollMagic with webpack

- src/components/MobileNaviBar.css
Modified css file for hamburger menu for older mobile browsers
> added older css animation syntax

- package.json
> add sass loader for webpack

- src/conf/category-tag-mapping-table.js
> modify src/conf/category-tag-mapping-table.js

- src/lib/constants.js
- added 亞洲森林浩劫
- removed 2016 總統大選
> Change subnav item

- spec/actions/articles.test.js
- spec/actions/mocks/article.js
- spec/actions/mocks/articles.js
- spec/actions/mocks/more-articles.js
- spec/actions/mocks/tags.js
- spec/actions/tags.test.js
- spec/reducers/articles.test.js
- src/reducers/article.js
- src/reducers/articles.js
- src/reducers/index.js
redux state will look like the following obj after code change
```
{
// entities will be in this obj, like tags, articles, authors, categories ...etc
entities: {
articles: {
'post-slug-1': {
// here goes to post details
},
'post-slug-2': {
// here goes to post details
}
},
tags: {
'tag-id-1': {
// here goes to tag details
},
'tag-id-2': {
// here goes to tag details
}
}
},
taggedArticles: {
'tag-1': {
isFetching: false,
error: null,
items: ['post-slug-1'],
nextUrl: null // null means no more to load
lastUpdated: 1234567890,
},
'tag-2': {
isFetching: false,
error: null,
items: ['post-slug-2'],
nextUrl: 'http://localhost:3030/posts%3Fmax_results%3D1%26where%3D%7B%22tags%22%3A%7B%22%24in%22%3A%5B%22572315331cece3ae858dffe3%22%5D%7D%7D%26page%3D2%26embedded%3D%7B%22authors%22%3A1%2C%22tags%22% …
```
> code change for articles reducer

- spec/actions/articles.test.js
- spec/reducers/articles.test.js
- src/actions/articles.js
> do nothing if articles are already loaded

- package.json
- src/containers/Home.js
> fix bug, fetchData should return promise

- server/server.js
- server/views/500.ejs
> show error msg while rendering components on server side

- src/components/article/HeadingAuthor.js
- src/components/article/HeadingAuthor.scss
- src/containers/Article.js
- src/containers/Article.scss
- src/themes/variables.scss
Add content to the HeadingAuthor component
> Add content to HeadingAuthor

- package.json
- server/server.js
- src/actions/article.js
- src/lib/custom-error.js
- src/reducers/device.js
- src/reducers/index.js
- add NotFoundError, InternalServerError and FatalError
- create NotFoundError and InternalServerError when fetching article
occurs error
- add fatalError in redux state
- code refactor for device reducer
@garfieldduck
> response 404 page while article is not found

- api/config.js
- src/components/Footer.css
- src/components/article/Author.js
- src/components/article/BottomAuthor.js
- src/components/article/BottomAuthor.scss
- src/components/article/index.js
- src/containers/Article.js
- src/themes/bootstrap.overrides.scss
added the author block in the bottom of the article page
> add the author block in the bottom

- .bootstraprc
- src/components/SubNavBar.scss
- src/themes/bootstrap-variables.scss
- src/themes/common-variables.scss
- src/themes/pre-bootstrap-customization.scss
- src/themes/variables.scss
- webpack/dev.config.js
- webpack/prod.config.js
integrate bootstrap on webpack
speparate bootstrap-variables.scss from variable.scss
update .bootstraprc
@garfieldduck
> integrate bootstrap

- package.json
- src/components/Footer.js
- src/components/article/BottomAuthor.js
- src/components/article/BottomAuthor.scss
- src/components/article/HeadingAuthor.js
- src/components/article/PublishDate.js
- src/components/article/PublishDate.scss
- src/components/article/index.js
- src/containers/Article.js
- src/containers/Article.scss
- src/routes/index.js
- src/themes/bootstrap.overrides.scss
- src/themes/common-variables.scss
- src/themes/pre-bootstrap-customization.scss
- add article title
- add react-intl for displaying publish date
- add outer and inner max-width definition for Article
- adjust Bootstrap global font & color styles
- adjust HeadingAuthor styles
- adjust BottomAuthor styles
- adjust Footer styles
> Article title & date with article styles adjusted

- src/components/article/BottomAuthor.js
- src/components/article/PublishDate.js
- src/containers/Article.js
fix unnecessary code according to Nick's comments
> fix bugs in PR #190

- src/actions/articles.js
- src/reducers/articles.js
> fix infinite fetching articles

- src/components/article/BlockAlignmentWrapper.scss
- src/themes/bootstrap.overrides.scss
- src/themes/common-variables.scss
> update our custom css style

- api/actions/index.js
- api/actions/loadGroups.js
- spec/src/actions/groups.test.js
- src/actions/groups.js
- src/components/article/BlockAlignmentWrapper.scss
- src/themes/bootstrap.overrides.scss
- src/themes/common-variables.scss
> add postcategories api endpoint on FE

- api/actions/loadArticles.js
- src/components/article/BottomAuthor.js
- src/components/article/BottomTags.js
- src/utils/get-article-embedded-query.js
- add request to get and combine author images into returning article data (in front-end api - 'loadArticles')
- add author images obtained from the front-end api to BottomAuthor
- fix the warning of missing keys in links of BottomTag
> add author images

- package.json
- src/components/Daily.js
- src/components/Features.js
- src/components/Tags.js
- src/containers/UserPage.js
- src/middleware/api.js
- src/reducers/paginate.js
and avoid direct require full lodash library to reduce client side byte size.
https://github.com/lodash/lodash/releases/tag/4.0.0
> Upgrade lodash

- api/actions/loadArticles.js
- api/actions/loadGroups.js
- api/constants.js
- package.json
- src/components/article/BlockAlignmentWrapper.scss
- src/components/article/Image.js
- src/components/article/Image.scss
- src/components/article/ImageDiff.js
- src/components/article/ImageDiff.scss
- src/components/article/PublishDate.js
- src/components/article/getArticleComponent.js
- src/constants/ui-settings.js
- src/lib/FitwidthMixin.js
- src/lib/screen-type.js
- webpack/dev.config.js
- Add image lazy loading function with one blurred image as placeholder loaded in advance and another original image
- update webpack-isomorphic-tools to the latest version
- fixed warning caused by PublishDate
- prepare files for ImageDiff
> Add image lazy loading function with blurred image fade-in effect

- src/components/article/Image.js
- src/components/article/ImageDiff.js
- src/components/article/ImageDiff.scss
- src/lib/FitwidthMixin.js
- static/asset/slider-button.svg
- webpack/webpack-isomorphic-tools.js
- Add slidable image comparator using html input
- update webpack-isomorphic-tool to avoid problems related to sass files
> Add ImageDiff - Comparator of Two Images

- src/components/article/LeadingImage.js
- src/containers/Article.js
> render null if no hero image

- api/actions/loadArticles.js
> fix bug. JSON.parse occurs error when query.embedded is undefined

- src/components/Footer.css
- src/components/article/Introduction.js
including the Footer.css for the logo size and component Introduction for the empty string.
> fixed some bugs

- api/actions/loadArticles.js
- src/actions/article.js
- src/components/article/BottomRelateds.js
- src/components/article/BottomRelateds.scss
- src/components/article/index.js
- src/containers/Article.js
- src/utils/article-nested-entity-methods.js
> Add Relateds

- src/components/article/Image.js
- src/components/article/Image.scss
- src/components/article/ImageDiff.js
- src/components/article/ImageDiff.scss
- src/components/mixins/FitwidthMixin.js
- replace fake images in ImageDiff with real images
- add description to ImageDiff and Image
> Add image description and replace fake images in ImageDiff

- src/components/article/package.json
> Update src/components/article/package.json. rename pkg name

- src/components/article/.npmignore
- src/components/article/package.json
> Update .npmignore and package.json

- .eslintignore
- src/components/article/package.json
- src/components/article/webpack.bootstrap.config.js
> Webpack bootstrap by bootstrap-loader and package bootstrap styles

- src/components/navigation/DesktopNavBar.js
- src/components/navigation/DesktopNavBar.scss
- src/components/navigation/MobileNavBar.js
- src/components/navigation/MobileNavBar.scss
- src/containers/NavBar.css
- src/containers/NavBar.js
- src/lib/constants.js
- src/themes/animation.scss
- add facebook, twitter sharing buttons
- add Line sharing button (mobile only)
- add article title for Twitter sharing
- use webpack to import svg images
- remove unnecessary sass prefix
> Mobile navigation bar with sharing buttons

- server/views/index.ejs
- src/components/article/InfoBox.js
- src/components/article/InfoBox.scss
- src/themes/bootstrap.overrides.scss
- src/themes/common-variables.scss
- src/themes/font-mixins.scss
- src/themes/pre-bootstrap-customization.scss
- static/asset/infobox-logo.svg
Only mobile version, waiting for desktop and tablet spec.
@garfieldduck
> Style tunning according to new design

- src/components/article/BottomTags.scss
- src/components/article/Introduction.js
- src/components/article/Introduction.scss
- src/components/navigation/HeaderProgress.scss
- src/containers/App.js
- src/containers/App.scss
- src/themes/common-variables.scss
- src/themes/pre-bootstrap-customization.scss
- Change styles for BottomTag, Introduction and ProgressBar
- Set overflow-x as hidden for the App container
> Change styles for App, BottomTag, Introduction and ProgressBar

- src/components/Daily.js
- src/components/article/Introduction.js
mini-refine for revamp branch for component key
> mini-refine for revamp branch for component key

- package.json
- src/components/article/Audio.js
- src/components/article/Audio.scss
- src/components/article/Body.js
- src/components/article/CircleProgressButton.js
- src/components/article/CircleProgressButton.scss
- src/components/article/InfoBox.js
- src/components/navigation/DesktopNavBar.js
- src/themes/common-variables.scss
- static/asset/play-icon.svg
Use ```react-addons-css-transition-group``` to do css transition animation for Audio controller.
@garfieldduck
> Audio component and some style tuning

- src/components/navigation/DesktopNavBar.js
- src/lib/date-transformer.js
- src/middleware/api.js
1. make the var to const
2. fixed a eslint warning
> some minor issues

- src/components/article/Audio.js
- src/components/article/Audio.scss
- src/components/article/CircleProgressButton.js
- src/components/article/Image.js
- src/components/article/slideshow/slideshow.js
- src/components/article/slideshow/slideshow.scss
- src/themes/common-variables.scss
> Style tunning and add isToShowDescription as a prop of Image component

- .gitignore
- src/components/article/Audio.scss
- src/components/article/BlockQuote.scss
- src/components/article/Body.scss
- src/components/article/Introduction.scss
- src/components/article/Paragraph.scss
- src/components/article/PublishDate.js
- src/components/navigation/SubNavBar.scss
- src/containers/Article.scss
- src/themes/bootstrap.overrides.scss
- src/themes/common-variables.scss
- Extract font-weight into common-variables
- Fix a bug in PublishDate
- Center content on desktop
> Extract font-weight into common-variables

- src/components/article/Annotation.js
- src/components/article/Annotation.scss
- src/components/article/BlockQuote.js
- src/components/article/Body.scss
- src/components/article/Common.scss
- src/components/article/Embedded.js
- src/components/article/HeadingAuthor.js
- src/components/article/Image.js
- src/components/article/Paragraph.scss
- src/components/article/PublishDate.js
- src/components/article/Youtube.js
- src/components/article/Youtube.scss
- src/components/article/getArticleComponent.js
- src/components/article/index.js
- src/components/article/slideshow/slideshow.js
- src/components/article/slideshow/slideshow.scss
- src/containers/Article.js
> CSS updates, style tuning of Embedded component and Annotation Component

- src/actions/header.js
- src/components/article/Common.scss
- src/components/navigation/NavMenu.js
- src/containers/Article.js
- src/containers/NavBar.js
- src/reducers/header.js
- src/themes/common-variables.scss
Display topic box if the article is part of a topic
> Display topic box if the article is part of a topic

- src/actions/article.js
- src/components/navigation/NavMenu.js
- src/components/navigation/TopicPopup.js
- src/containers/Article.js
- src/routes/index.js
use router-router's Link to switch between articles
> Enable single-page-app function for Article

- src/components/navigation/NavMenu.js
- src/components/navigation/TopicPopup.js
- Add LazyLoad for the Topic navigation
- small bug fix
> Add LazyLoad for the Topic navigation

- src/components/article/Body.js
- src/components/article/Body.scss
- src/components/article/BottomRelateds.js
- src/components/article/BottomRelateds.scss
- src/components/article/Common.scss
- src/components/navigation/TopicPopup.scss
- src/constants/index.js
- src/containers/Article.js
- adjust styles
- add load more function
TODO:
- combine topic if the article is in the one of the topic
> Revamp related articles in the bottom according to the new spec

- src/components/Footer.scss
- src/components/article/BottomRelateds.scss
- src/components/navigation/NavMenu.scss
- src/components/navigation/TopicPopup.js
- src/components/navigation/TopicPopup.scss
Adjust font sizes after the bootstrap base font size adjusted
> Adjust font sizes 

- src/components/article/BottomRelateds.js
- src/containers/Article.js
Display topic article list in 'BottomRelated' if the article belongs to a topic
> Display topic article list if the article belongs to a topic

- src/actions/articles.js
- src/components/article/Audio.js
- src/containers/Article.js
- src/reducers/index.js
> Fix missing related articles

- src/components/navigation/NavMenu.js
- src/components/navigation/NavMenu.scss
- src/containers/Article.js
- Show topic list on desktop header for index pages
- Show scrolled header on index pages
> Show topic list on desktop header for index pages

- src/components/Daily.js
- src/components/FeaturesItem.js
- src/components/Tags.js
- src/components/TopNews.js
- src/components/article/BottomTags.js
- src/components/navigation/NavMenu.js
- src/components/navigation/SubNavBar.js
- src/conf/list-id.js
- src/constants/index.js
- src/containers/Article.js
> Use Link of react-router to replace a tag

- src/components/Daily.js
- src/components/FeaturesItem.js
- src/components/Tags.js
- src/components/TopNews.js
- src/containers/Article.js
> Code refactor for src/containers/Article.js and replace <a> by <Link> of react-router

- src/components/Daily.css
- src/containers/Category.js
Add category title on the top of the category index page
> Add category title on the top of the category index page

- src/containers/Article.js
> Fix article content missing while switching to different article page

- src/components/article/HeaderOne.js
- src/components/article/HeaderTwo.js
Fix html display problem inside h1 and h2
> Fix html display problem inside h1 and h2

- src/components/article/Body.js
- src/components/article/Paragraph.scss
- src/themes/bootstrap.overrides.scss
- src/themes/common-variables.scss
- fix hover styles of the global css
- link styles of Paragraph
- fix problems in displaying common styles of some article components
> Fix hover style of the global css, link styles of Paragraph, width of some article components

- server/views/404.ejs
- server/views/500.ejs
- src/components/Daily.css
- src/components/FeaturesItem.css
- src/components/More.css
- src/components/TopNews.css
- src/containers/NavBar.css
- src/themes/common-variables.scss
- fix article list styles of the homepage to avoid strange lines keeping appearing
- remove unnecessary font-family declarations
> Fix article list styles of the homepage, remove unnecessary font-family

- concatCssFiles.js
- package.json
- src/actions/articles.js
- src/components/article/Embedded.js
- src/containers/Article.js
- src/lib/string-processor.js
@garfieldduck @hcchien 
ref to this [PR](https://github.com/twreporter/keystone/pull/91)
> Handle Embedded Component

- src/components/article/Body.js
- src/components/article/HeaderOne.js
- src/components/article/HeaderOne.scss
- src/containers/Article.scss
- src/themes/common-variables.scss
- add the italic style
- fix bug in h1
- adjust styles for h1&h2
> Add italic font style, adjust h1 and h2

- src/components/article/HeadingAuthor.scss
- src/components/article/Introduction.js
- src/components/article/Introduction.scss
- src/components/article/Paragraph.scss
- src/components/article/PublishDate.scss
- src/components/article/ShareBt.js
- src/components/article/ShareBt.scss
- src/components/navigation/NavMenu.scss
- src/themes/common-variables.scss
- hide Line share button on desktop
- change font styles of the author list
- enable HTML rendering function in the Introduction
- hide donation text on tablet when users scroll down the menu
> hide Line share button, enable HTML rendering in Introduction, change font styles

- src/components/article/Audio.js
- src/components/article/BlockQuote.js
- src/components/article/BlockQuote.scss
- src/components/article/Body.js
- src/components/article/Common.scss
- src/components/article/LeadingImage.scss
- src/components/article/Youtube.js
- src/components/article/getArticleComponent.js
- src/components/article/slideshow/slideshow.js
- src/themes/common-variables.scss
> Blockquote and LeadingImage style

- src/components/Daily.css
- src/components/Footer.js
- src/components/Tags.css
- src/components/Tags.js
- src/components/navigation/NavMenu.js
- src/components/navigation/NavMenu.scss
- src/components/navigation/SubNavBar.js
- src/containers/Category.js
- src/containers/Topic.js
- show categories when user scrolls down on desktop
- fix tags listing page alignment problem
- refine tag listing style
- replace footer's div with html5 tag
- add topic title in topic's index page
- change title to h1 for SEO
@nickhsine
> Adjust tag and index page navbar

- src/conf/category-tag-mapping-table.js
- src/containers/Category.js
- src/containers/Tag.js
- src/containers/Topic.js
Fetching data on client side successfully.
Change meta of html on client side.
@garfieldduck
> Fix bug. Fetching Data on client side.

- src/actions/article.js
- src/actions/articles.js
- src/components/article/BlockQuote.scss
Show url to fetch in the redux log
Do not fetch related articles while articleId is not provided
New line in text inside the QuoteBy component
@garfieldduck
> Several Enhancement

- src/components/Daily.css
- src/components/More.css
- src/components/Tags.js
- src/components/TopNews.css
- src/components/navigation/NavMenu.js
- src/components/navigation/NavMenu.scss
- src/constants/index.js
- src/containers/Topic.js
- show topic title on navbar when scrolled down
- fix photography NavBar style
- replace 500 font-weight with 400 in some CSS
- change some items name in the menu
@nickhsine
> Show topic title on navbar when scrolled down, Fix photography NavBar style

- CHANGELOG.md
- gulpfile.js
- package.json
> Use gulpfile to build pkg and upgrade to 1.0.8

- src/components/Tags.css
- src/components/Tags.js
- src/components/article/BottomRelateds.scss
- src/components/navigation/SubNavBar.scss
- src/containers/Article.js
- src/containers/Article.scss
- src/themes/common-variables.scss
- Show image and text placeholders when loading articles
- Fix photography list item styling
@nickhsine
> Show placeholders when loading articles

- src/components/navigation/NavMenu.js
Hide the category bar on tablet
> Hide the category bar on tablet

- src/components/Tags.js
- src/components/article/Annotation.scss
- src/containers/Article.js
- src/containers/Article.scss
- static/asset/icon-topic-arrow-right.svg
* Update Annotation style	
* Pass eslint
@garfieldduck
> Add subtitle and change style of topic name

- src/components/article/Annotation.js
- src/components/article/Audio.js
- src/components/article/BlockQuote.js
- src/components/article/Common.scss
- src/components/article/HeaderOne.js
- src/components/article/HeaderTwo.js
- src/components/article/HeadingAuthor.js
- src/components/article/InfoBox.js
- src/components/article/Introduction.js
- src/components/article/Introduction.scss
- src/components/article/OrderedList.js
- src/components/article/Paragraph.js
- src/components/article/Paragraph.scss
- src/components/article/UnorderedList.js
- src/containers/Article.js
- src/containers/Article.scss
- src/themes/common-variables.scss
- set photography style for the article page
- remove separate text color settings for each components in Article
> Set photography style for the article page

- src/actions/articles.js
- src/components/article/BlockAlignmentWrapper.scss
- src/containers/Article.js
1. Use feature articles as fallback when there is no related articles
2. Update BlockAlignmentWrapper.scss
@garfieldduck
> Use feature articles as fallback when there is no related articles

- src/actions/articles.js
- src/components/article/BlockAlignmentWrapper.scss
- src/components/article/InfoBox.js
- src/constants/index.js
- src/containers/Article.js
- src/containers/Home.js
- src/containers/Photography.js
- src/reducers/articles.js
- fetch feature articles only when if needed
- Replace fetchFeatureArticlesIfNeeded by fetchFeatureArticles
- Update InfoBox.js 
- Fix photography page showing feature articles whose style is not 'photography'
> Fix bugs and some updates

- src/components/Footer.js
- src/components/Footer.scss
- src/components/navigation/NavMenu.js
- src/components/navigation/NavMenu.scss
- src/components/navigation/SubNavBar.js
- src/constants/index.js
- src/containers/App.js
- src/containers/App.scss
- src/containers/Article.js
- src/containers/Photography.js
- src/themes/common-variables.scss
> Add dark theme for photography channel

- src/components/article/OrderedList.js
- src/components/article/Paragraph.scss
- src/components/article/UnorderedList.js
- src/components/navigation/NavCommon.scss
- src/containers/Article.scss
- src/containers/NavBar.js
- Show the reading progress bar and box shadow for the header of Photography
- Render HTML in ordered and unordered list
@nickhsine
> Render HTML in ordered and unordered list, Show the reading progress bar and box shadow for the header of Photography

- LICENSE.txt
- README.md
- package.json
- server/server.js
- server/views/index.ejs
- src/components/navigation/SearchBox.js
- src/conf/service.js
- src/constants/index.js
- src/containers/Search.js
- src/containers/Search.scss
- src/routes/index.js
- add google search page to display the user queried results
- update license for the site revamp
@hcchien  @nickhsine
> Add google search page to display the user queried results, update license for revamp

- src/components/article/Audio.scss
- src/components/article/BlockQuote.scss
- src/components/article/InfoBox.scss
Fix text colors of some components to let text shown properly in the Photography page
> Fix text colors of some components to let text shown properly in Photography

- src/components/article/OrderedList.scss
- src/components/article/UnorderedList.scss
- src/components/navigation/NavMenu.scss
- src/components/navigation/TopicPopup.scss
- src/containers/Article.scss
* change letter spacing
* refine Navbar's padding and margin
* update link style
* fix ul and ol list alignment
> Style tuning

- src/components/article/Annotation.scss
- src/components/article/BlockQuote.scss
- src/components/article/InfoBox.scss
- src/components/article/Paragraph.scss
> Lines are broken at newline characters

- src/components/article/BlockAlignmentWrapper.scss
- src/components/article/Common.scss
- src/components/article/OrderedList.js
- src/components/article/UnorderedList.js
- src/themes/common-variables.scss
> Fix OrderedList and UnorderedList component

- src/components/article/Annotation.scss
- src/components/article/Image.js
* fix LazyLoad images alignment
> fix LazyLoad images alignment

- src/containers/Blank.js
- src/containers/Category.js
- src/containers/Home.js
- src/containers/Photography.js
- src/containers/Tag.js
- src/containers/Topic.js
>  Only one default export allowed per module

- src/components/navigation/NavMenu.js
- src/themes/bootstrap.overrides.scss
* fix Photography topic popup
* add a class to take out unwanted article link hover effects
> fix Photography topic popup, add class to remove unwanted hover effects

- src/components/Features.css
- src/components/TopNews.js
- src/utils/image-composer.js
> Replace storage link prefix

- src/components/Daily.css
- src/components/FeaturesItem.css
> Style tunning

- src/components/Daily.css
- src/components/Footer.scss
- src/components/More.css
- src/components/TopNews.css
- src/components/navigation/NavMenu.js
- src/constants/index.js
- src/containers/NavBar.js
- fix top margin of the footer
- adjust characters limits of the article header
- fix styles of the 'more article' button
- fix the display problem of indicator on the Home slider
@nickhsine
> Fine tune index page styling, Leave enough padding for header when page changed

- CHANGELOG.md
- package.json
- src/components/Footer.js
- src/constants/footer.js
- src/constants/index.js
- src/containers/Article.js
> Do not use feature articles as fallback on those footer article page

- api/actions/loadArticles.js
- src/components/article/Annotation.scss
- src/components/article/Audio.scss
- src/components/article/BlockQuote.scss
- src/components/article/BottomRelateds.scss
- src/components/article/InfoBox.scss
- src/components/article/Introduction.scss
- src/components/article/Paragraph.scss
- src/components/navigation/NavMenu.scss
- src/constants/index.js
- src/containers/Article.js
- src/containers/Article.scss
- src/themes/bootstrap.overrides.scss
- src/themes/common-variables.scss
- src/themes/pre-bootstrap-customization.scss
- Use lodash to get author image
- Add article SEO tag
- Global css styles tuning
@nickhsine
> Use lodash to get author image, Add article SEO tag, Global css styles tuning

- src/components/Daily.js
- src/components/FeaturesItem.js
- src/components/Footer.js
- src/components/Link.js
- src/components/Tags.js
- src/components/TopNews.js
- src/components/article/BottomRelateds.js
- src/components/article/BottomTags.js
- src/components/article/PageNavigation.js
- src/components/navigation/NavMenu.js
- src/components/navigation/SubNavBar.js
- src/components/navigation/TopicPopup.js
- src/constants/article-styles.js
- src/constants/index.js
> Use <a> tag rather than Link of react-router when the style of article is interactive

- package.json
- src/containers/Article.scss
- src/store/configureStore.js
- src/utils/get-list-id.js
- src/utils/replace-storage-url-prefix.js
- Replace global.__DEVELOPMENT__ by __DEVELOPMENT__
- Less top padding for h2 style
- Hide log on production	
@garfieldduck
> Hide log on production and some updates

- src/components/navigation/TopicPopup.js
- src/containers/Article.js
- src/containers/NavBar.js
> Replace url prefix and show all the articles of the same topic in Popup and related section

- src/actions/header.js
- src/components/Tags.css
- src/components/navigation/NavCommon.scss
- src/components/navigation/NavMenu.scss
- src/components/navigation/TopicPopup.scss
- src/constants/index.js
- src/containers/Article.scss
- src/containers/NavBar.js
- src/reducers/header.js
- fix topic item overflow
- refine top spacing as page switches
- hide read progress bar as page switches
- refine topic text display on header
> fix topic item overflow, refine various header stylings

- package.json
- src/components/article/BottomRelateds.js
- src/components/article/Image.js
- src/components/article/Image.scss
- src/components/article/slideshow/slideshow.js
- src/components/navigation/TopicPopup.js
- src/constants/ui-settings.js
- src/themes/common-variables.scss
- switch the LazyLoad package to improve performance
@nickhsine
> refine LazyLoad to improve performance

- package.json
- src/components/article/ImageDiff.js
- src/containers/NavBar.js
refine image diff slider for ios, IE
> refine image diff

- src/components/article/BottomRelateds.js
- src/components/article/Image.js
- src/components/article/slideshow/slideshow.js
- src/components/navigation/TopicPopup.js
- src/constants/ui-settings.js
configure LazyLoad to improve performance
> configure LazyLoad

- package.json
- src/components/article/Image.js
- src/components/article/ImageDiff.js
- src/components/article/ImageDiff.scss
- src/constants/ui-settings.js
- src/themes/bootstrap.overrides.scss
- improve LazyLoad
- enable NatoSansTC
- change ImageDiff
> Improve LazyLoad, enable NatoSansTC, change ImageDiff

- src/utils/replace-storage-url-prefix.js
> Add error handling for replaceStorageUrlPrefix

- src/components/TopNews.css
- src/components/article/BottomRelateds.scss
- src/components/article/Image.scss
- src/components/article/OrderedList.js
- src/components/article/UnorderedList.js
- src/components/article/UnorderedList.scss
- src/components/article/slideshow/slides.scss
- src/components/navigation/SubNavBar.scss
fix bugs caused by the removal of the reset.css
@nickhsine
> fix bugs caused by the removal of the reset.css

- src/components/article/OrderedList.js
- src/components/article/UnorderedList.js
> [WORKAROUND] render ordered list and unordered list well

- server/server.js
- src/components/article/BottomTags.scss
Fix facebook sharing properties
> Fix facebook sharing properties

- server/server.js
> fix ogImage

- server/server.js
- src/constants/index.js
- src/containers/Article.js
> fix ogImage url

- server/server.js
- src/components/article/BottomRelateds.js
- replaceStorageUrlPrefix image url of BottomRelateds
@garfieldduck @hcchien
> [IMPORTANT UPDATE] 	Add Cache-Control in the response header.

- server/server.js
This reverts commit 99f91f9d7381cad31cadec06f69636f785adf094.
> Revert "No compression. Let compression handled by ATS"

- src/components/article/BottomRelateds.scss
- src/components/article/BottomTags.scss
- src/components/navigation/TopicPopup.scss
- src/containers/Article.scss
- src/containers/NavBar.js
- src/containers/Search.js
* refine css link
* extract google search ID
* add debounce events for header
> header and css fine tune

- src/components/article/Audio.js
- src/components/article/Audio.scss
- src/components/article/BottomRelateds.js
- src/components/article/BottomRelateds.scss
- src/components/article/Image.scss
- src/components/article/ShareBt.scss
- src/components/article/slideshow/navigation.scss
- src/components/navigation/NavMenu.scss
- src/components/navigation/TopicPopup.scss
- src/themes/common-variables.scss
- add proper css animations to control buttons on the slideshows
- optimize css files related to image display
- remove unnecessary event listener
- refine css of Audio
@nickhsine
> Image css files optimizations, Remove unnecessary event listener, Refine css of Audio

- package.json
- server/server.js
- src/containers/App.js
- src/containers/Article.js
- src/containers/Search.js
- display the document title of Article on the client side
@nickhsine
> Fix the document title of Article on the client side

- api/actions/loadArticles.js
- api/actions/loadGroups.js
- api/config.sample.js
Code change because api/config.js changed as well.
@garfieldduck @hcchien
> Update for calling remote RESTful API

- server/server.js
- src/components/navigation/NavMenu.js
- src/components/navigation/NavMenu.scss
- src/components/navigation/SearchBox.js
- src/components/navigation/SearchBox.scss
- src/containers/Search.js
- move search box from burger menu to nav bar
- add logo icon in the nav bar while scrolling down
- remove server side google site search script
- modify SearchBox component
@garfieldduck
> Search Box tuning

- api/actions/loadArticles.js
- api/actions/loadGroups.js
- api/config.sample.js
This reverts commit 7d4295c88600fbd2b071b8d627383318be759749.
> Revert "Update for calling remote RESTful API"

- server/config.js
- src/constants/index.js
- src/containers/Home.js
> Update site meta

- src/components/article/Image.scss
- src/components/navigation/NavMenu.scss
* Refine image styles
* Refine position of the Navlogo
@nickhsine
> Refine image styles, Refine position of the Navlogo

- package.json
- server/server.js
- src/themes/bootstrap.overrides.scss
- static/asset/font.css
* modify the polyfill service
* optimize webfont loading
@nickhsine
> modify the polyfill service, optimize webfont loading

- api/constants.js
- server/server.js
- src/components/article/Image.scss
* fix image lazyload effect
* add google amp
* extend api timeout
@nickhsine
> fix image lazyload effect, add google amp, extend api timeout

- package.json
- src/components/article/LeadingVideo.css
- src/components/article/LeadingVideo.js
- src/components/article/LeadingVideo.scss
- src/containers/Article.js
- use video.js pkg
- render video when browser width is bigger than desktop
- render heroImage when browser width is less than desktop
- not to render LeadingImage when LeadingVideo is existed
> Leading video

- src/components/navigation/Bookmarks.js
- src/components/navigation/Bookmarks.scss
> Add left and right arrow

- src/components/article/BlockAlignmentWrapper.scss
> Fix align bug

- README.md
- server/server.js
- src/themes/pre-bootstrap-customization.scss
- static/asset/font.css
> Webfont: Use Adobe Typekit

- server/server.js
- src/components/article/Introduction.scss
- src/components/article/Paragraph.scss
- src/themes/common-variables.scss
> CSS change for readability

- src/components/article/Annotation.scss
- src/components/navigation/NavMenu.js
- src/components/navigation/NavMenu.scss
- src/containers/Article.scss
[SEO] remove multiple h1
[style-change] for better readability
> Readability and SEO

- src/containers/App.js
- src/containers/Article.js
- src/containers/NavBar.js
- [Bug fix] show progress bar on long form article
- [enhancement] make scroll smoothly
@garfieldduck
> Bug fix and client side performance enhancement

- src/components/navigation/SubNavBar.js
- src/components/navigation/SubNavBar.scss
> [seo] replace <h1> by <span>

- src/components/article/Annotation.scss
- src/components/article/BlockQuote.scss
- src/components/article/Common.scss
- src/components/article/InfoBox.scss
- src/components/article/Paragraph.scss
> [style-change] larger the text for better readability

- api/actions/loadArticles.js
- Change /posts/${slug} to /posts?where={"slug": ${slug}}, which can get
much less response back
[REF](https://github.com/twreporter/tr-projects-rest/pull/77)
@garfieldduck
> [Enhancement] Shrink api response size

- api/api.js
- api/config.example.js
- package.json
- cache response by url with expire time
- serve cached data if existed
@garfieldduck
> [Enhancement] Use Redis as the cache layer between FE server and RESTful webservice

- server/server.js
> [Bug] Add Cache-Control header only for status 200

- server/server.js
- src/containers/Article.js
[Update] add dateModified and update logo and mainEntityOfPage
[Update] Update the article title on client side
> MicroData update

- server/server.js
- src/components/Daily.js
- src/components/FeaturesItem.js
- src/components/Tags.js
- src/components/TopNews.js
- src/components/navigation/NavMenu.js
- src/components/navigation/SubNavBar.js
- src/containers/Category.js
- src/containers/Home.js
- src/containers/Tag.js
- src/containers/Topic.js
JSON-LD ```WebSite, Organization and SiteNavigationElement``` are only shown on index page.
```Article``` MicroData is only shown on article page.
> Update MicroData and JSON-LD 

- src/components/navigation/Bookmarks.js
disable react router and set target="_blank" when style of bookmarked article is interactive
> [Update] Update bookmark.

- src/conf/sub-nav-path.js
- change items on the subnavbar
> [Update] change items on the subnavbar

- .gitignore
- src/components/article/Image.js
- src/themes/common-variables.scss
- Improve article lazyload effect on desktop devices
- Change the outer shadow of the article loading placeholder
@nickhsine
> [Update] Improve article lazyload effect on desktop devices

- src/components/FontChangeButton.js
- src/components/FontChangeButton.scss
- src/components/article/Annotation.scss
- src/components/article/BlockQuote.scss
- src/components/article/Body.js
- src/components/article/Body.scss
- src/components/article/Image.js
- src/components/article/Paragraph.scss
- src/components/article/ShareBt.js
- src/components/article/ShareBt.scss
- src/containers/Article.js
function completed with simple animation.
> font size changing

- src/conf/sub-nav-path.js
- add '一例一休吵什麼？'
- remove '亞洲森林浩劫'
> [Update] Items on the sub-navigation bar

- src/components/topic/Cards.js
- src/components/topic/Topic.scss
- src/containers/Home.js
1. Change the url of PromotaionBanner on index page
2. Avoid horizontal scrolling on mobile devices
3. Use 'infographics' as the prefix of the url path when article style
is interactive
> [Update] Several updates after reviewing

- src/containers/Home.js
This reverts commit 2c0f4fae525bcde66774ab3bfbf4224914555f87.
> Revert "[Update] Hide PromotionBanner on index page"

- src/conf/sub-nav-path.js
> [Update] Update sub-nav-path.js

- src/components/navigation/NavMenu.js
- Fixed the problem of navigation header displaying wrong content when page type is review
> [Bug] Fix navigation header is not showing properly on review pages

- src/constants/index.js
- fix the problem that the text of 'LOAD_MORE_ARTICLES' is not displaying properly
> [Bug] Text of 'LOAD_MORE_ARTICLES' is not displaying properly

- src/components/article/BottomRelateds.js
- src/components/article/BottomRelateds.scss
- add translateY effect for the `BottomRelateds` component
> [Update] Hover style of the BottomRelateds

- src/components/Html.js
- src/containers/Home.js
- Integrate HotJar analytics
- adjust the meta for SEO for the search bar
> [Update] Add HotJar tracking code, adjust the meta for SEO

- api/api.js
- server/server.js
- src/routes/index.js
- Add health check endpoint.
- Increase expire time of redis record.
- Increase max-age of Cache-Control directive.
@garfieldduck
> [Update] Update caching.

- src/components/article/BlockAlignmentWrapper.js
- src/components/article/Body.js
- src/components/article/Image.js
- src/components/article/Image.scss
- src/containers/Article.js
fix the bug of image placeholder of photography page
> [Update] fix image placeholder color for photography

- package.json
- processes.json
Add processes.json for pm2 to start up the servers.
processes.json is used in the Dockerfile. 
https://console.cloud.google.com/code/develop/commit/dockers/7fa2a9b2eee0?project=coastal-run-106202&authuser=1
@garfieldduck
> Add processes.json and update package.json

- package.json
- server/server.js
- src/components/Html.js
- src/constants/strings.js
- src/containers/Article.js
- src/containers/Category.js
- src/containers/Home.js
- src/containers/Photography.js
- src/containers/Tag.js
- src/containers/Topic.js
- src/containers/TopicLandingPage.js
> [Update] Replace react-document-meta by react-helmet

- server/server.js
> [Update] Update server/server.js. Decrease the cache time

- CHANGELOG.md
- src/components/ArticleList.js
- src/containers/Photography.js
Fix several errors in constants used in the photography page
> [Bug] Photography page is not displaying any article

- CHANGELOG.md
- src/conf/sub-nav-path.js
- original link: `/a/protect-animal-no-killing-ch1`
- updated link: `/topics/no-killing-policy`
> [Update] Change link of the animal protection project

- CHANGELOG.md
- src/components/navigation/NavMenu.js
> [Update] Show categories on navbar when device is not mobile

- src/actions/author.js
- src/constants/author-page.js
- src/containers/Author.js
- src/reducers/author.js
- Move state formatting from action creator to reducer
- Add author collection items per page from 3 to 5
> [AuthorPage] Move functions from action to reducer

- api/actions/__test__/load-articles.test.js
> [Update] update api/actions/__test__/load-articles.test.js.

- CHANGELOG.md
- api/actions/__test__/load-topics.test.js
- api/actions/__test__/search-authors.test.js
- api/actions/__test__/search-posts.test.js
- api/actions/search-authors.js
- api/actions/search-posts.js
- package.json
- yarn.lock
> [Testing] api testing is done

- src/actions/authors.js
prevent rebasing conflict and violating the lint rule
> fix trivial bugs

- src/actions/__test__/article.test.js
- src/actions/__test__/author-articles.test.js
- src/actions/__test__/authors.test.js
- src/actions/__test__/mocks/author-articles.js
- src/actions/__test__/mocks/authors.js
- src/actions/author-articles.js
- src/actions/authors.js
- src/reducers/authors.js
1. Testing Completion 
1.  author-articles.test.js 
2. authors.test.js 
1. Modification 
1.  article.test.js 
2. authors.js
> action testing is completely done 

- src/reducers/__test__/articles.test.js
- src/reducers/__test__/header.test.js
- src/reducers/__test__/index.test.js
- src/reducers/index.js
> Add reducers testing of articles,  header, and index

- .gitignore
- CHANGELOG.md
- src/components/Footer.js
- src/components/navigation/NavMenu.js
- Track click events of header and footer donation buttons separately
- Avoid yarn error log from being committed into the repo
@nickhsine
> [Update] Add GA tracking for donation buttons

- CHANGELOG.md
- src/components/Html.js
- src/components/article/LeadingImage.js
- src/components/article/LeadingImage.scss
- yarn.lock
- defer script tag to avoid blocking
- load typekit asynchronously
- not to lazy load leading image
> [Update] Code updates according to pagespeed advice

- CHANGELOG.md
- src/components/navigation/SubNavBar.js
- src/conf/sub-nav-path.js
> - [Update] Update the navigation bar

- CHANGELOG.md
- src/components/shared/PromotionBanner.scss
- src/containers/Home.js
- Add two promotional banners
- Add hover styles for the banners
@nickhsine
> [Update] Add promotional banners

- CHANGELOG.md
- src/components/article/Annotation.scss
Fix the style bugs in the annotation box:
- Unexpected dotted lines
- Unexpected link color
@nickhsine
> [Bug] Showing unexpected dotted lines in the annotaion box

- CHANGELOG.md
- src/conf/sub-nav-path.js
Update the navigation for the topic `taiwan-pesticide`
> [Update] Update the navigation bar

- .gitignore
- CHANGELOG.md
- package.json
- src/components/Html.js
- src/conf/sub-nav-path.js
- src/containers/Home.js
Modules
1. category 
2. header
> Index page revamp

- CHANGELOG.md
- package.json
- src/conf/category-list-id.js
- src/conf/category-uri.js
- src/constants/category-strings.js
- src/containers/Category.js
- src/containers/Home.js
Version jumps to 2.0.0
@hanyulo @YuCJ @garfieldduck
> Upgrade to 2.0.0

- .circleci/config.yml
> Integrate with circleci

- src/containers/Home.js
1. Rewrite import structure of twreporter-index-page-components
2. latest-section -> header-section
> [Update] Home page

- CHANGELOG.md
- package.json
- src/conf/category-list-id.js
- src/conf/category-uri.js
- src/constants/category-strings.js
- src/containers/Article.js
- src/containers/Category.js
- src/containers/Home.js
- src/containers/Photography.js
- src/containers/Tag.js
- src/containers/Topic.js
- src/containers/TopicLandingPage.js
- src/reducers/index.js
- src/utils/image-processor.js
> Provide srcset of image for each category in categories_section and fix react duplicate key bug.

- CHANGELOG.md
- package.json
- src/containers/Home.js
> Bug fix. Open post with interactive style on another tab

- CHANGELOG.md
- package.json
- yarn.lock
- [Feature] Add tool bar in Article page
> Upgrade to 2.1.0

- CHANGELOG.md
- package.json
- src/containers/Home.js
- yarn.lock
Done
1. Modification for refactored scroll fadein
2. Add non-animated background div
> [Update] refactor scroll fadein

- CHANGELOG.md
- package.json
- src/containers/Article.js
- src/containers/Article.scss
- yarn.lock
- Remove _sendPageLevelAction when Article unmount
- Prevent fetch full post if is already fetching
- Fix ArticlePlaceholder
> Fix Article bugs

- .circleci/config.yml
> Update .circleci/config.yml. Separate staging and release branches

- package.json
- processes.json
- webpack/prod.config.js
> API configuration for staging environment

- package.json
- src/components/Layout.js
- src/components/article/Embedded.js
- src/components/article/Image.js
- src/components/article/ImageDiff.js
- src/components/article/LeadingImage.js
- src/components/article/LeadingVideo.js
- src/components/article/PageNavigation.js
- src/components/article/mixins/FitwidthMixin.js
- src/components/article/tools/DesktopArticleTools.scss
- src/components/article/tools/MobileArticleTools.scss
- src/containers/App.js
- src/containers/Article.js
- yarn.lock
- Update article tool styles
- Remove lazyload on photograph articles
- Update ref to callback function
- Remove raf in Article
- Check screen type in Article
- Replace pure-render-mixin with PureComponent
> Update Article components

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- package.json
- src/containers/Home.js
> Code updates after twreporter-react-index-page-component upgrade

- package.json
- src/components/Layout.js
- src/containers/Home.js
- yarn.lock
- Update twreporter-redux version
- Add loading spinner on homepage
> Add loading spinner on homepage

- CHANGELOG.md
- package.json
- src/containers/Home.js
- yarn.lock
Currently hide news-letter section.
> Upgrade to 2.1.12

- CHANGELOG.md
- package.json
- src/containers/Home.js
- yarn.lock
Hide news-letter section for now.
> Release 2.1.12 on staging

- CHANGELOG.md
- src/components/article/slideshow/navigation.js
- src/components/article/slideshow/slideshow.js
Slideshow will switch to the correct one on switching button clicked on Android
@nickhsine
> [Bug] Slideshow will switch to the correct one on Android

- CHANGELOG.md
- src/components/article/slideshow/slides.js
- src/components/article/slideshow/slides.scss
- src/components/article/slideshow/slideshow.js
- src/components/article/slideshow/thumbnails.scss
Update the image slideshow to let it fit the height of every image displaying on the viewport
@nickhsine
> [Update] image slideshow to let it fit the height of every image

- src/components/article/ReadingProgress.js
- src/containers/Home.js
- src/index.js
- src/routes/index.js
- webpack/dev.config.js
- webpack/prod.config.js
> Code splitting and dynamic bundle loading by webpack

- CHANGELOG.md
- src/containers/Home.js
Fix Google structure data errors in Google Search Console
> Fix Google structure data errors

- .babelrc
- CHANGELOG.md
- package.json
- src/client.js
- src/routes/index.js
- src/store/configureStore.js
- webpack/dev.config.js
- yarn.lock
> Code refactors and remove react-hot-loader.

- CHANGELOG.md
- README.md
- package.json
- src/components/Layout.js
- src/components/article/BottomRelateds.scss
- src/components/article/LeadingImage.js
- src/components/article/LeadingImage.scss
- src/components/article/article-meta.js
- src/components/article/title-row-above.js
- src/components/article/title-row-upon.js
- src/components/article/zoom-in-leading-image.js
- src/constants/customized-article-path.js
- src/constants/page-themes.js
- src/containers/App.js
- src/containers/Article.js
- src/containers/Article.scss
- src/containers/SherrySpecial.js
- src/helpers/url-recognizer.js
- src/helpers/with-layout.js
- src/routes/index.js
- src/server.js
- src/themes/common-variables.js
- src/themes/common-variables.scss
- src/themes/screen.js
- yarn.lock
Wait for review 
Everything is done. 
1. CHANGELOG
2. Version Number ( twreporter-components )
3. yarn.lock
> [Update] dynamic themes by keystone plus customized article page

- CHANGELOG.md
- src/containers/TopicLandingPage.scss
for youtube player or other embedded items
> Add TopicLandingPage topic description iframe max-width 100%

- package.json
- processes.json
- webpack.config.js
This reverts commit f03639c2716608d4963a76ebd8b440430b9a6560, reversing
changes made to d06679677d9072c31c1c10a3c98398e5b3fc8230.
> Revert "Merge branch 'staging' into master"

- CHANGELOG.md
- package.json
- src/containers/Home.js
- src/helpers/with-layout.js
- webpack.config.js
- Scroll to the target section on homepage if section parameter is existed
@hanyulo
> Bump version to 2.4.6

- CHANGELOG.md
- package.json
- src/components/authors/AuthorSearchBox.scss
- src/containers/Author.js
- src/containers/AuthorsList.js
Fix author list page style problem, including
1. search icon in the search box is too big
2. default author image is missing
> Bump version to 2.5.3

- CHANGELOG.md
- package.json
- src/components/article/Image.js
[Bug] fix print image abnormally
>  Bump version to 2.5.4

- src/components/article/Embedded.js
- src/components/article/ShareBt.scss
- src/components/shared/PrintButton.scss
- remove outline of button
- hidden embedded block while printing
> Style chagne

- CHANGELOG.md
- README.md
- package.json
- src/client.js
- src/routes/index.js
- [Bug] fix image too big problem
- Update README.md and comments
> Bump version to 2.5.6

- .babelrc
- CHANGELOG.md
- package.json
- src/components/article/BlockQuote.scss
- src/components/article/getArticleComponent.js
- src/containers/Article.js
- src/helpers/Html.js
- src/routes/index.js
- webpack.config.js
- yarn.lock
- Decrease BlockQuote font-size to 20px
- Add dynamic import with react-loadable
> Add react-loadable and decrease BlockQuote font-size

- package.json
- src/constants/category-strings.js
- src/containers/Home.js
- src/store/configureStore.js
- webpack.config.js
- Changes the name of politicsAndEconomy in category strings on homepage (Home.js)
- Changes the name of politicsAndEconomy in siteNavigationJSONLD (Home.js)
> Change category strings of homepage.

- CHANGELOG.md
- src/components/shared/FullScreenImage.js
- src/components/shared/Image.js
> Avoid `setState` on unmounted or mounting component

- CHANGELOG.md
- src/store/local-storage.js
> Bug fix - Author list page and author page behaves abnormally after using localStorage data

- CHANGELOG.md
- package.json
- src/components/article/Embedded.js
Pack dataset first, then add it to element.attributes
> Update embedded component

- CHANGELOG.md
- package.json
- yarn.lock
- Update @twreporter/react-components from 4.0.7 to 4.0.9
> Bump version to 2.7.7

- src/store/browser-storage.js
- src/store/configure-store.js
Update browser cache(cache redux state) mechanism
> Release 3.0.0 with bug fixed

- service-worker/service-worker.tmpl
Update service-worker/service-worker.tmpl
> Release 3.0.0 with new patch

- src/containers/App.js
> Release 3.0.0 on staging with wording changes

- .circleci/config.yml
> Update config.yml. Use file to store local env variables

- src/components/shared/DonationBox.js
- src/containers/Article.js
This commit adds a donation box to the bottom of each article.
> Add donation box to article pages

- package.json
- src/components/about-us/constants/section-02/media-members.js
- src/components/about-us/section-02/index.js
- yarn.lock
- Change member photo and modify line height of introduction words in about-us page section2
- Update @twreporter/react-components to 4.1.4
> Minor layout changes of about-us page and  update @twreporter/react-components

- CHANGELOG.md
- package.json
- yarn.lock
> Fix 500 error caused by browser extension(NewsGuard)

- CHANGELOG.md
- src/components/ErrorBoundary.js
> Render instructions instead of error 500 page if an error is catched by ErrorBoundary

- CHANGELOG.md
- package.json
- src/components/side-bar/article-side-bar.js
- src/themes/screen.js
- yarn.lock
> long form article side bar UI changes

- package.json
- src/components/shared/DonationBox.js
- yarn.lock
This PR adds ga click event to button in article donation box and is different from [that PR](https://github.com/twreporter/twreporter-react-components/pull/118), which adds click events to donation section in homepage and footer.
> Add GA events to donation button in article pages

- src/containers/app-shell.js
This patch adds missing `_setNextPopupToNextMonth` function in App class
> Bug fix. Update src/containers/app-shell.js

- Dockerfile
- package.json
- src/managers/layout-manager.js
- src/routes.js
- yarn.lock
Bug fixed: pass `releaseBranch` prop to universal header.
Bug fixed: load data for article page on the server side.
Update Dockerfile. Update to `node@10.15-slim` which matches the node image of circleci builds.
Update to `@twreporter/universal-header@2.0.3-beta-4`
> Bugs fixed and Dockerfile update.

- src/components/about-us/section-04/index.js
- src/components/about-us/section-05/index.js
This patch fixes about-us page layout in section4 and section5.
> Fix about-us page layout

- CHANGELOG.md
- package.json
- src/components/about-us/constants/data/sidebar-link.js
- src/components/side-bar/aboutus-page-side-bar.js
- src/constants/index.js
- yarn.lock
This patch should be released with https://github.com/twreporter/CI-CD/pull/91
> Revise donation page link

- CHANGELOG.md
- src/managers/layout-manager.js
- Reduce about 8kB bundle size of main chunk
> Not to import all modules from `@twrerporter/universal-header`

- src/containers/Article.js
- https://github.com/twreporter/react-article-components/pull/30
- https://github.com/twreporter/twreporter-redux/pull/31
Please see the above PRs before this one.
> Use redux store to cache settings.fontLevel on browser

- src/app.js
- src/containers/app-shell.js
- src/managers/ui-manager.js
**Problem**: When route changed, the `render` prop of `react-router` will be triggered before the 'CHANGE_SELECTED_POST` action being dispatched. The action is to update the current post. So it will get the wrong `post` data to build the layout.
**Solution**: Change `AppShell` to a redux container in order to update the layout when `selectedPost` in the redux store changed.
> Fix worng seleted-page gived to uiManager

- package.json
- src/containers/Article.js
- yarn.lock
As editors requirement, they want related posts sorted in certain order.
> change order of related posts

- CHANGELOG.md
- package.json
- yarn.lock
bug fix: lacks of categories' post in categories section on index page
> prepare for v4.3.13-rc.1

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to test @twreporter/react-article-components@1.0.18-beta.1 on staging environment.
https://github.com/twreporter/twreporter-npm-packages/pull/35
> Release v4.3.14-rc.1 on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to release stable v4.3.14 on staging environment.
> Release v4.3.14 on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to release v4.3.14 on production environment.
> Release v4.3.14 on production

- CHANGELOG.md
- package.json
- src/helpers/Html.js
- yarn.lock
This PR is to test `v4.3.15-rc.1` on staging.
> Release v4.3.15-rc.1 on staging

- CHANGELOG.md
- package.json
This PR is to release v4.3.15 on both staging and production.
> prepare for releasing v4.3.15

- CHANGELOG.md
- package.json
- src/helpers/Html.js
- yarn.lock
This PR is to trigger CI to deploy latest code base on production.
> Release v4.3.15 on production

- CHANGELOG.md
- package.json
- yarn.lock
- upgrade @twreporter/react-article-components@^1.0.18
- update package.json and CHANGELOG.md
> prepare for v4.3.16-rc.1

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CI to deploy `v4.3.16` on staging servers.
> Release v4.3.16 on staging

- CHANGELOG.md
- package.json
- src/helpers/Html.js
- yarn.lock
This PR is to trigger CI to deploy `v4.3.16` on production servers.
> Release v4.3.16 on production

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to test v4.3.18-rc.1 version on staging environment.
> prepare for v4.3.18-rc.1

- CHANGELOG.md
- package.json
- src/components/topic/related/index.js
- yarn.lock
This PR is to trigger circleCI to deploy `v4.3.18-rc.1` code base on staging environment.
> Release v4.3.18-rc.1 on staging

- CHANGELOG.md
- package.json
- src/components/topic/related/index.js
- yarn.lock
This PR is to trigger CircleCI to deploy v4.3.18-rc.2 code base on staging environment
> Release v4.3.18-rc.2 on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to test `@twreporter/react-article-components@1.0.20-beta.4`.
Test cases:
1. https://kanbanflow.com/t/zX1aLAS3
2. https://kanbanflow.com/t/4dTmfHaL
3. https://kanbanflow.com/t/RJVA6Xi5
4. https://kanbanflow.com/t/2EWJDqnK
5. https://kanbanflow.com/t/2Wh1j1Q2
6. https://kanbanflow.com/t/4BH66Eo5
7. https://kanbanflow.com/t/2ieEpdCW
8. https://kanbanflow.com/t/2GqpUUgZ
9. https://kanbanflow.com/t/2E4GmzdB
10. https://kanbanflow.com/t/fnAe22Jm
11. https://kanbanflow.com/t/fp8ce375
> test v4.3.18-rc.3

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to deploy `v4.3.18-rc.3` code base on staging environment.
> Release v4.3.18-rc.3 on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to test release candidate `v4.3.18-rc.4`, which achieves 
article v2 fine tuning according to mockup 
- `article@2.0.2`
- `article@2.1.2`
- `article@2.1.3`
> test v4.3.18-rc.4

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.3.18-rc.4` on staging environment.
> Release v4.3.18-rc.4 on staging.

- CHANGELOG.md
- package.json
- yarn.lock
This PR is aim to tune styles of article aside tool bar.
For more, see mockup `article@2.1.4(FineTune)`
> test v4.3.19-rc.1

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.3.19-rc.1` on staging environment.
> Release v4.3.19-rc.1 on staging

- CHANGELOG.md
- package.json
- yarn.lock
includes load more funcitonality and aside tools style tune of article page
Zeplin mockup tag
`article@2.1.0(Related)`
`article@2.1.4(FineTune)`
> test v4.3.19-rc.2

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.3.19-rc.2` on staging environment
> Release v4.3.19-rc.2 on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.3.19` on staging environment.
> Release v4.3.19 on staging

- CHANGELOG.md
- package.json
- src/client.js
- yarn.lock
https://github.com/twreporter/twreporter-npm-packages/pull/53
> v4.3.20: jump to anchor position if URI contains `#${anchorName}`

- CHANGELOG.md
- package.json
- src/client.js
- yarn.lock
This PR is to trigger CircleCI to build and deploy v4.3.20 on staging environment.
> Release v4.3.20 on staging

- CHANGELOG.md
- package.json
- src/client.js
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.3.20` on production environment.
> Release v4.3.20 on production

- CHANGELOG.md
- package.json
- yarn.lock
This PR upgrades `@twreporter/react-article-components` to `@1.0.24-beta.1`,
which fine tunes the `embed` component of article page.
> test v4.4.1-rc.1

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.4.1-rc.1` code base on staging environment.
> Release `v4.4.1-rc.1` on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR upgrades `@twreporter/react-article-components` to `@1.0.24`,
which fine tunes 
- embed component
- slideshow component
of article page.
> test v4.4.1-rc.2

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.4.1-rc.2` on staging environment.
> Release `v4.4.1-rc.2` on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.4.1` on staging environment.
> Release `v4.4.1` on staging

- CHANGELOG.md
- src/components/author-page/author-data.js
KanbanFlow Task: https://kanbanflow.com/t/2gQQC3aX
> Update style of AuthorPage Bio

- CHANGELOG.md
> Release v4.4.3

- .circleci/config.yml
This patch disables DLC and removes redundant steps during the workflow.
> Disable DLC and remove redundant steps

- CHANGELOG.md
- package.json
- src/components/Pagination.js
- src/containers/Category.js
- src/containers/Home.js
- src/containers/ServiceWorkerFallbackPage.js
- src/containers/Tag.js
- src/containers/Topics.js
- yarn.lock
- Fix home spinner displayed logic
- Fix wrong query retrieving with react-router
- Prevent invalid search query page input 
- Bump @twreporter/react-article-components to 1.0.25-beta.4
> Several fix for v4.4.5

- CHANGELOG.md
- package.json
- src/client.js
- src/utils/hash-link-scroll.js
- yarn.lock
[KanbanFlow Card](https://kanbanflow.com/t/H9a4fnka)
> [Bug] Fix `mobile-slide-down-menu` where `議題` button doesn't scroll to right position

- package.json
- src/utils/hash-link-scroll.js
- yarn.lock
[Kanban Flow Card](https://kanbanflow.com/t/H9a4fnka)
> [Bug] Can't scroll to correct anchor on index page

- .circleci/config.yml
This patch fixes the incorrect test operator with OR.
> Fix incorrect test operator

- package.json
- yarn.lock
This patch update @twreporter npm packages:
- Upgrade @twreporter/core to v1.1.2-rc.2
- Upgrade @twreporter/index-page to v1.0.6-rc.3
- Upgrade @twreporter/react-article-components to v1.0.26-rc.2
- Upgrade @twreporter/react-components to v8.0.3-rc.2
- Upgrade @twreporter/universal-header to v2.1.2-rc.3
> Upgrade @twreporter npm packages

- CHANGELOG.md
- package.json
- src/containers/TopicLandingPage.js
This PR aims to merge cherry-picked hotfix commits on release branch into master
> Merge hotfix commits on release into master

- .circleci/config.yml
This patch integrates kubernetes configs to deploy on GKE on
the staging/next branch.
> chore: integrate kubernetes configs to deploy

- .circleci/config.yml
This patch updates circleci config for the new release environment.
Also, wraps the constant with the environment variable
$GOOGLE_PROJECT_ID.
> chore: Update config for release environment

- CHANGELOG.md
- build-babel-preset.js
- package.json
- src/client.js
- webpack.config.js
- yarn.lock
This PR is to trigger CircleCI to build and deploy `v4.4.9-rc.2` on staging environment.
> Release v4.4.9-rc.2 on staging 

- CHANGELOG.md
- package.json
- service-worker/service-worker-generator.js
This PR is to trigger CircleCI to build and deploy v4.4.9 on staging environment.
> Release v4.4.9 on staging

- CHANGELOG.md
- package.json
- src/client.js
- src/components/ErrorBoundary.js
- src/components/Pagination.js
- src/components/topic/search-box.js
- src/containers/AuthorsList.js
- src/containers/Photography.js
- src/containers/TopicLandingPage.js
- src/containers/web-push.js
- src/data-loaders/author-page.js
- src/data-loaders/bookmark-list.js
- src/data-loaders/bookmark-widget.js
- src/data-loaders/photography-page.js
- src/express/middlewares/auth.js
- src/express/middlewares/init-redux-store.js
- src/express/server.js
- src/global-env.js
- src/logger/index.js
- src/logger/noop.js
- src/logger/winston-logger.js
- src/mock-data/index-page-categories.json
- src/server.js
- webpack.config.js
- yarn.lock
- Use `winston` and `@google-cloud/logging-winston` on server side 
- Use `console` on client side
- Send logs to stackdriver logging by `@google-cloud/logging-winston` on Production environment
- Print logs on console by `winston` on Development environment
> Integrate logger with winston and @google-cloud/logging-winston

- .circleci/config.yml
- CHANGELOG.md
- package.json
- src/client.js
- src/components/ErrorBoundary.js
- src/components/Pagination.js
- src/components/topic/search-box.js
- src/containers/AuthorsList.js
- src/containers/TopicLandingPage.js
- src/containers/web-push.js
- src/data-loaders/author-page.js
- src/data-loaders/bookmark-list.js
- src/data-loaders/bookmark-widget.js
- src/data-loaders/photography-page.js
- src/express/server.js
- src/global-env.js
- src/logger/index.js
- src/logger/winston-logger.js
- src/server.js
https://kanbanflow.com/t/gi1gCf6C
> refactor: specify stackdriver resource object

- CHANGELOG.md
- package.json
- service-worker/service-worker-generator.js
This PR is to trigger CircleCI to build and deploy 4.4.10 on staging environment.
> Release 4.4.10 on staging.

- CHANGELOG.md
- package.json
- src/express/middlewares/data-loader.js
This PR is to trigger CircleCI to build and deploy 4.4.12-rc.1 on staging environment.
> Release 4.4.12-rc.1 on staging.

- CHANGELOG.md
- package.json
- src/express/middlewares/data-loader.js
This PR is to trigger CircleCI to build and deploy 4.4.12 on staging environment.
> Release 4.4.12 on staging

- src/containers/Category.js
- src/containers/Tag.js
Fix the listing page problem that one item will remain on page for a moment when user click another page.
https://kanbanflow.com/t/KW1U4dnY
> Fix list bug

- CHANGELOG.md
- package.json
- src/containers/web-push.js
This PR is to trigger CircleCI to build and deploy v4.4.17 on staging environment.
> Release 4.4.17 on staging

- CHANGELOG.md
- package.json
- src/containers/web-push.js
- yarn.lock
This PR is to trigger CircleCI to build and deploy v4.4.18 on staging environment.
> Release v4.4.18 on staging

- src/components/about-us/section-02/content-carousel-list.js
This patch fixes section2 where arrows of photography department can not
click
> fix: section 2 of about us

- CHANGELOG.md
- package.json
- yarn.lock
- @twreporter/react-article-components@1.1.8-rc.0
> chore: update dependency on staging

- package.json
- yarn.lock
- @twreporter/react-article-components@1.1.8
> chore: update dependency (#1636)

- src/client.js
Our application is a SPA (Single Page Application).
In our app, we send requests to API webservices to get data if that data is not in the redux store.
In other words, if data is already in the redux state, we won't send requests.
There will be a problem of stale data.
For example,
1. end user goes to page A. App will fetch page A data and store it in redux state.
2. end user goes to page B. App will fetch page B data and store it in redux state.
3. end user goes to page A again. App won't fetch page A data since it already in the redux state.
If end users don't refresh the web page, the data will be always in the redux store. 
Therefore, end users might see the stale data even the data is already updated.
Force to reload the web page if the web page has not been reloaded for more than …
> fix: reload page after one day to avoid stale data

- CHANGELOG.md
- package.json
- src/utils/shallow-clone-entity.js
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.0 on staging environment.
> chore(release): 4.5.0 on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.6 on staging environment.
> chore(release): v4.5.6 on staging

- CHANGELOG.md
- package.json
- src/constants/prop-types.js
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.6 on production environment.
> chore(release): v4.5.6 on production

- CHANGELOG.md
- package.json
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.7 on staging environment.
> chore(release): v4.5.7 on staging

- CHANGELOG.md
- package.json
- src/constants/prop-types.js
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.7 on production environment.
> chore(release): v4.5.7 on production

- CHANGELOG.md
- package.json
- service-worker/service-worker-generator.js
- src/constants/status-code.js
- src/express/server.js
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.8 on preview server.
> chore(release): v4.5.8 on preview branch

- CHANGELOG.md
- package.json
- service-worker/service-worker-generator.js
- src/constants/status-code.js
- src/express/server.js
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.8 on staging environment.
> chore(release): v4.5.8 on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.10 on staging environment.
> chore: v4.5.10 on staging

- CHANGELOG.md
- package.json
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.10 on production environment.
> chore: v4.5.10 on production

- src/express/server.js
In our [error reporting system](https://console.cloud.google.com/errors/CPLAmLXIk_eGPg?time=P30D&project=coastal-run-106202), there are lots of `Not Acceptable` error.
However, `Not Acceptable` error (status code: 406), which is a client error, should not be reported.
In our old logic, if we encounter 406 error, we will redirect that error to 500 error page.
Therefore, error reporting system will be triggered and the worst part is we return the wrong response (response should be 406, rather than 500).
In the new way, we not only handle 404 and 500 error (redirect to error page), but also 
log error information if error.statusCode < 500, and report error if error.statusCode >= 500.
However, since our error page only handle 404 and 500 error, we need to refactor …
> fix: handle other errors except for 404 and 500 errors

- CHANGELOG.md
- package.json
- src/data-loaders/category-list-page.js
- src/express/server.js
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.11 on staging environment.
> chore: v4.5.11 on staging 

- CHANGELOG.md
- package.json
- src/data-loaders/author-page.js
- src/express/server.js
- yarn.lock
This PR is to trigger CircleCI to build and deploy v4.5.12 on staging environment.
> chore: release v4.5.12 on staging 

- src/express/middlewares/data-loader.js
- src/express/server.js
We used to delegate the errors from data loaders to the custom error handler.
In custom error handler, we log client error (through stackdriver logging) and report server error (through stackdriver error reporting).
However, errors from data loaders should be treated in different way.
For example, data loaders will request data from backend servers, and that request might cause client
error, like 400 (Bad request).
If we pass 400 error to custom error handler, that error will be only logged, not reported.
We, as developers, need to know why that request causes 400 error.
Therefore, this patch adds another error handler for data loaders middleware.
> refactor: update express server error handling

- CHANGELOG.md
- package.json
- src/data-loaders/author-page.js
- src/express/middlewares/data-loader.js
- src/express/server.js
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.13 on staging environment.
> chore: release 4.5.13 on staging environment

- .circleci/config.yml
- CHANGELOG.md
- package.json
- yarn.lock
This PR triggers CircleCI to build and deploy v4.5.14 on staging environment.
> chore: release 4.5.14 on staging

- src/html.js
@taylrj 
Wrong rss feed in html header
> Update html.js with right rss feed

- package.json
- src/containers/Home.js
- yarn.lock
https://github.com/twreporter/twreporter-npm-packages/pull/166 is required for this change.
> feat: add podcast box section to homepage

- package.json
- yarn.lock
- @twreporter/index-page@1.2.1
- @twreporter/react-article-components@1.2.13
- @twreporter/react-components@8.4.0
> chore: update dep

- src/components/author-page/author-collection.js
- src/containers/Author.js
- src/containers/AuthorsList.js
https://github.com/twreporter/twreporter-npm-packages/pull/170 is required for this change.
> refactor: tweak data path according to @twreporter/redux updates

- src/components/author-page/author-collection.js
This patch updates article collection display logic to show article
number 0 when an author has no article.
> refactor: show article number when an author has no article

- src/components/about-us/index.js
- src/components/side-bar/base-components.js
- src/containers/Home.js
[story-48][task-1] fix the anchor on index-page
> fix: incorrect anchor position on index page

- package.json
- yarn.lock
- @twreporter/index-page@1.2.4-rc.0
- @twreporter/react-article-components@1.3.1-rc.0
- @twreporter/react-components@8.4.3-rc.0
> chore: upgrade npm packages

- package.json
- yarn.lock
- @twreporter/index-page@1.2.4
- @twreporter/react-article-components@1.3.1
- @twreporter/react-components@8.4.3
> chore(release): upgrade npm packages

- CHANGELOG.md
- package.json
This patch bumps version to v4.6.11-rc.3.
> chore: bump version to v4.6.11-rc.3

- yarn.lock
This patch adds the inconsistent yarn.lock of
@twreporter/react-article-components.
> fix: inconsistent yarn.lock

- package.json
- for testing header 2.0 on staging
> chore: test @twreporter/universal-header v2.2.0-rc.4

- src/components/web-push.js
This patch updates comments in web-push component in single-lines
instead of multi-line since styled-compnent does not support.
> fix: update comments to single lines

- src/components/web-push.js
- src/containers/app-shell.js
- z-index setting
- web-push: 1001
- header: 1000
- other component: 999 or below
> fix: fix header/web-push z-index & transparent warpper style

- package.json
- yarn.lock
- react-article-components: v1.4.6-rc.0
> chore: update @twreporter module version

- src/client.js
This patch push user id datalayer for gtm analysis & separate gtm data to different environments.
> feat: add user id datalayer

- src/constants/site-meta.js
- src/containers/Home.js
- set og:updated_time today(2021-12-30)
> fix: add og:updated_time in header

- src/constants/feature-flags.js
- src/containers/app-shell.js
add sticky to top css to ensure header animations when scrolling up/down
ref: https://github.com/twreporter/twreporter-npm-packages/blob/7c596606067293077e43976cb35f876235031030/packages/universal-header/src/containers/header.js#L31
> fix: fix header animation issue

- CHANGELOG.md
- package.json
This patch update CHANGELOG.md & package.json to bump version to v4.7.17-rc.3
> chore: bump version to v4.7.17-rc.3

- Makefile
- config.js
- webpack-dev-server.js
This patch add DEV_HOST environment variable toggle as webpack dev server host
> fix: add mobile test support

- src/components/about-us/constants/section-02/carousel-markup.js
- src/components/about-us/constants/section-02/categories.js
- src/components/about-us/constants/section-02/category-ids.js
- src/components/about-us/constants/section-02/headcount-per-page.js
Address https://twreporter-org.atlassian.net/browse/TWREPORTER-337.
This change updates to about-us to show current colleagues.
> refactor: update about-us

- src/containers/Article.js
- src/routes.js
This patch inject `releaseBranch` props to article component for article tool bar.
> feat: inject releaseBranch into article component

- src/containers/Home.js
Address [TWREPORTER-412](https://twreporter-org.atlassian.net/browse/TWREPORTER-412)
https://github.com/twreporter/twreporter-npm-packages/pull/290 is required by this change.
> refactor: replace the NewsletterSection with JuniorBoxSection

- src/data-loaders/photography-page.js
This patch fixes data loader for photography page where it can not get posts on server side rendering.
> fix: photography page data loader

- package.json
- yarn.lock
This change updates @twreporter npm packages:
- @twreporter/index-page@1.4.0-rc.2
- @twreporter/react-article-components@1.7.0-rc.0
> chore: update @twreporter npm packages

- package.json
- yarn.lock
This reverts commit c0b6d6cc3daba467c0cd5cef31979ca06c3a402a.
> Revert "chore: update @twreporter npm packages (#2250)"

- package.json
- src/containers/Home.js
- src/routes.js
- yarn.lock
fix https://app.asana.com/0/1202896150264815/1203309142649553/f
companion PR: https://github.com/twreporter/twreporter-npm-packages/pull/326
> fix: add releaseBranch props to home

- src/app.js
- src/containers/app-shell.js
- `/* eslint-disable react/display-name */` setting is to resolve eslint error of `component definition is missing display name`.
- [ref](https://bobbyhadz.com/blog/react-component-is-missing-display-name#:~:text=Set%20the%20displayName%20property%20on,line%20react%2Fdisplay%2Dname%20.)
> fix: pass location info to header component

- src/constants/data-loaders.js
- src/constants/routes.js
- src/containers/Category.js
- src/containers/Latest.js
- src/data-loaders/index.js
- src/data-loaders/latest-page.js
- src/routes.js
- src/testing-server.js
This patch add latest page.
To test it, please correspond to [`twreporter-npm-packages` PR #345](https://github.com/twreporter/twreporter-npm-packages/pull/345)
> feat: add latest page

- src/components/about-us/constants/section-02/org-intro.js
- src/components/about-us/constants/section-03/awards-name.json
- src/components/about-us/section-02/index.js
- section 2 intro wording
- add new awards & adjust awards order
> fix: about-us

- src/containers/Category-old.js
- src/containers/Tag.js
This patch fix defect: [[release defect] tag 頁＆分類頁 title bar 的 margin 不是 45px ](https://app.asana.com/0/1203699264568808/1204019109526970/f)
> fix: list style

- src/app.js
https://app.asana.com/0/1203699264568808/1203983432530619/f
> fix: add font smoothing

- CHANGELOG.md
- package.json
> chore: bump version v4.10.1-rc.4

- CHANGELOG.md
- package.json
- src/app.js
> chore: release v4.10.1-rc.4 to staging

- .circleci/config.yml
> feat: enable dev branc

- CHANGELOG.md
- package.json
> chore: bump version v4.10.1-rc.7

- CHANGELOG.md
- package.json
> chore: bump version v4.10.1-rc.11

- src/components/member-page/member-data.js
- src/components/member-page/menu-list.js
- src/components/member-page/mobile-page/mobile-menu-list.js
- src/containers/Member.js
fix divider margin and role data
> fix: fix defects

- CHANGELOG.md
- package.json
bump version to v4.10.5-beta.2
> chore: bump version to v4.10.5-beta.2

- src/express/middlewares/data-loader.js
`Server error was caught by Express default error handler. Invalid URL: / TypeError [ERR_INVALID_URL]: Invalid URL: /`
> fix: fix new URL type problem

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.6-rc.0

- src/express/middlewares/data-loader.js
> fix: use original url.parse

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.6-rc.1

- CHANGELOG.md
- package.json
- src/express/middlewares/data-loader.js
> chore: test v4.10.6-rc.1 on staging

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.6-rc.2

- CHANGELOG.md
- package.json
- service-worker/service-worker-generator.js
- src/express/middlewares/data-loader-old.js
- src/express/middlewares/data-loader.js
> chore: test v4.10.6-rc.2 on staging

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.5-beta.3

- .circleci/config.yml
- Dockerfile
Downgrade to v12 to test an unknown bug on v16
> chore: downgrade to node v12.22.12

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.6-rc.3

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.5-beta.4

- src/components/member-page/donation.js
- src/constants/routes.js
[[會員制] 贊助紀錄頁](https://app.asana.com/0/1203699264568808/1204692921007276/f) defect
> fix: member donation page route and color

- .circleci/config.yml
- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.10.5-beta.5

- CHANGELOG.md
- package.json
- src/client.js
> chore: bump version to v4.10.5-beta.6

- src/components/member-page/email-subscription/index.js
[[會員制] 電子報訂閱變更頁](https://app.asana.com/0/1203699264568808/1204692921007274/f) defect
> fix: snackbar and H3 color

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.5-beta.7

- src/logger/winston-logger.js
fix import warning ([ref](https://cloud.google.com/nodejs/docs/reference/logging-winston/latest))
> fix: import winston module with require

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.10.6-rc.5

- CHANGELOG.md
- package.json
- src/logger/winston-logger.js
- yarn.lock
> chore: test 4.10.6-rc.5 on staging

- build-babel-preset.js
- package.json
- webpack.config.js
- yarn.lock
[20230531 文章頁 reload error](https://app.asana.com/0/0/1204754585032337/f)
`react-article-components` has some async functions need to convert to es5 syntax with babel.
> fix: apply `babel-loader` on react-article-components

- .circleci/config.yml
- Dockerfile
> chore: update node version to 16.14.2

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.6-rc.8

- build-babel-preset.js
- package.json
- yarn.lock
- @babel/plugin-transform-runtime would make about-us page crash
> fix: remove @babel/plugin-transform-runtime

- src/components/member-page/member-data.js
- src/constants/routes.js
[[會員制] 會員 wording 調整](https://app.asana.com/0/1203699264568808/1204831081121332/f)
> feat: change route to account

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.5-beta.8

- src/components/member-page/email-subscription/subscription-options.js
- src/components/member-page/member-data.js
- src/components/member-page/member-role-card.js
- src/components/member-page/mobile-page/mobile-member-page.js
- src/containers/Member.js
- src/data-loaders/member-page.js
[[會員制] 會員專區的會員身份 API 串接](https://app.asana.com/0/1203699264568808/1204362012792382/f)
[go-api](https://github.com/twreporter/go-api/pull/555/files)
[npm-packages](https://github.com/twreporter/twreporter-npm-packages/pull/410)
> feat: get user data from state

- CHANGELOG.md
- package.json
- src/components/member-page/menu-list.js
- src/components/member-page/mobile-page/mobile-menu-list.js
- src/routes.js
> chore: bump version to v4.10.5-beta.11

- src/components/member-page/menu-list.js
> fix: change showing text

- CHANGELOG.md
- package.json
> chore: bump version to v4.10.5-beta.14

- CHANGELOG.md
- package.json
- src/containers/Member.js
[[defect] 在未登入的情況下，點選訂閱/訂閱電子報，需先登入，不可以直接進到電子報訂閱頁](https://app.asana.com/0/0/1204966623570377/f)
N/A
> fix: check member page auth state when csr

- build-babel-preset.js
- package.json
- yarn.lock
Reverts twreporter/twreporter-react#2533
> Revert "fix: remove @babel/plugin-transform-runtime"

- CHANGELOG.md
- package.json
- src/containers/Member.js
- src/express/middlewares/auth.js
[[defect] 在未登入的情況下，點選訂閱/訂閱電子報，需先登入，不可以直接進到電子報訂閱頁](https://app.asana.com/0/0/1204966623570377/f)
[ [spec change] 若 deactivated 的使用者在主網站為登入狀態，則登出](https://app.asana.com/0/0/1204967979635899/f)
N/A
> fix: defects

- CHANGELOG.md
- package.json
> chore: bump to @4.10.7 stable version

- CHANGELOG.md
- package.json
> chore: release @4.10.7 on staging

- CHANGELOG.md
- package.json
- yarn.lock
> chore: release @4.10.7 on production

- CHANGELOG.md
- package.json
- src/app.js
- src/components/membership-promo/banner.js
- src/components/membership-promo/more.js
- src/components/membership-promo/popup.js
- src/contexts/index.js
- src/hooks/index.js
- src/hooks/use-promo.js
- yarn.lock
[[會員制] 其他頁面站內導流（pop up）](https://app.asana.com/0/1203699264568808/1204934606026371/f)
[[會員制] 其他頁面站內導流（bottom banner）](https://app.asana.com/0/1203699264568808/1204984001934440/f)
- components
- add two kinds of promotions: Popup, Banner
- hook
- add usePromo to deal with bussiness logic
- context
- store promo related states
N/A
> feat: add membership promo champaign

- package.json
- yarn.lock
在數位敘事的 listing page ( https://www.twreporter.org/tag/630f029461ca4e07004ef530 ) 裡，多篇多媒體文章點擊後，文章沒有順利導到正確的網址；導致文章內容沒有正確呈現。
https://github.com/twreporter/twreporter-npm-packages/pull/416
> chore: update version to 4.10.8 and upgrade @twreporter/react-compoennts

- CHANGELOG.md
- package.json
- src/components/membership-promo/popup.js
[[defect] 專題頁出來之後，首頁/最新/專題集合頁/分類頁還是要出現 popup
](https://app.asana.com/0/0/1205178711230180/f)
N/A
> fix: `closePromo` been called in unexpected place

- CHANGELOG.md
- package.json
- src/components/photography/article-list.js
[[維運] 攝影頁的文章元件字重調整](https://app.asana.com/0/1203699264568808/1204386580283307/f)
> fix: change font weight to normal

- CHANGELOG.md
- package.json
- src/containers/BookmarkList.js
- src/containers/Member.js
- src/routes.js
[[會員制] 個人專區、我的書籤 metadata（phase 1）](https://app.asana.com/0/1203699264568808/1205230308764706/f)
> feat: booklist page metadata

- CHANGELOG.md
- package.json
- src/containers/Member.js
- src/routes.js
[[會員制] 電子報訂閱頁未登入時的 empty state](https://app.asana.com/0/1203699264568808/1205156951419952/f)
> feat: login page for member page

- src/app.js
- src/components/membership-promo/banner.js
- src/hooks/use-promo.js
[[會員制測試] 站內導流](https://app.asana.com/0/1203699264568808/1205245838889279/f)
N/A
> fix: membership promo defects

- CHANGELOG.md
- package.json
> chore: bump version to v4.11.0-rc.8

- src/containers/BookmarkList.js
> fix: forget to pass `releaseBranch` into `BookmarkList`

- CHANGELOG.md
- package.json
> chore: bump version to v4.11.0-rc.10

- CHANGELOG.md
- package.json
> chore: bump stable version to 4.11.0

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.11.1-rc.0

- .circleci/config.yml
- Dockerfile
- package.json
- yarn.lock
[[工程] upgrade nodejs to v18](https://app.asana.com/0/1203699264568808/1204298342406882/f)
https://github.com/twreporter/twreporter-npm-packages/pull/427
> chore: upgrade node to v18.17.1 (LTS)

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.11.1-rc.2

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.11.1-rc.3

- CHANGELOG.md
- package.json
- yarn.lock
> chore: test v4.11.1-rc.3 on staging

- CHANGELOG.md
- package.json
- src/client.js
- yarn.lock
> chore: test v4.11.1-rc.4 on staging

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.11.1-rc.5

- CHANGELOG.md
- package.json
- src/client.js
- yarn.lock
> chore: test v4.11.1-rc.5 on staging

- CHANGELOG.md
- package.json
- src/client.js
- yarn.lock
> chore: test v4.11.1-rc.6 on staging

- CHANGELOG.md
- package.json
- src/components/about-us/constants/section-02/category-ids.js
- src/components/about-us/constants/section-03/awards-name.json
- src/components/about-us/section-02/content-paginated-list.js
[[維運] 關於我們資料更新、增加區塊](https://app.asana.com/0/1203699264568808/1205329976610313/f) defects
> fix: add new award and sorting

- CHANGELOG.md
- package.json
- src/components/about-us/section-03/content-accordion-list.js
[[維運]關於我們-行高修改](https://app.asana.com/0/1203699264568808/1205648789166033/f)
> feat: section03 line height

- CHANGELOG.md
- package.json
- src/components/membership-promo/article-banner.js
- src/components/membership-promo/more.js
- src/containers/Article.js
- src/contexts/index.js
- yarn.lock
[[會員制] 文章頁 bottom banner](https://app.asana.com/0/1203699264568808/1205329976610294/f)
[npm-packages#447](https://github.com/twreporter/twreporter-npm-packages/pull/447)
> feat: article bottom banner

- src/express/middlewares/auth.js
[[會員制] 前端取得 role 資訊](https://app.asana.com/0/1203699264568808/1205536057963183/f)
related to PR https://github.com/twreporter/membership-fe/pull/843
N/A
> fix: update access token name & use wildcard domain

- CHANGELOG.md
- package.json
> chore: bump version to v4.12.0

- CHANGELOG.md
- package.json
- src/containers/Article.js
[[會員制] 文章頁 bottom banner加上身份判斷](https://app.asana.com/0/1203699264568808/1205810060034457/f) defects
> fix: typo role => roles

- CHANGELOG.md
- package.json
- src/containers/Article.js
[[會員制]閱讀文章篇數-前端](https://app.asana.com/0/1203699264568808/1205988685100788/f)
> feat: reading count by timer and height

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.12.2-rc.1

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.12.3

- src/app.js
- src/components/EmptyState.js
- src/components/member-page/donation.js
- src/components/member-page/member-role-card.js
- src/components/member-page/menu-list.js
- src/components/member-page/mobile-page/mobile-member-page.js
- src/components/member-page/mobile-page/mobile-menu-list.js
- src/components/membership-promo/article-banner.js
- src/components/membership-promo/banner.js
- src/components/membership-promo/index.js
- src/components/membership-promo/more.js
- src/components/membership-promo/popup.js
- src/containers/BookmarkList.js
- src/containers/Category.js
- src/containers/Latest.js
- src/containers/Member.js
- src/containers/app-shell.js
- src/contexts/index.js
- src/routes.js
[[資訊架構] 子分類 empty state](https://app.asana.com/0/1203699264568808/1206117666290864/f)
- add CoreContext for global var passing
- add EmptyState component
https://github.com/twreporter/twreporter-npm-packages/pull/474
> feat: add category page empty state

- src/containers/Article.js
[[會員制] 閱讀文章篇數、閱讀時間串接](https://app.asana.com/0/1203699264568808/1206008027632075/f) defects
> fix(src/containers/article): add beforeunload eventListener

- CHANGELOG.md
- package.json
- src/containers/Article.js
- src/testing-server.js
> fix(src/containers/article): trigger inactive timer

- src/components/skeleton.js
[[維運] 最新 skeleton 動畫](https://app.asana.com/0/1203699264568808/1206007354275603/f)
N/A
> feat: add animation for Skeleton component

- CHANGELOG.md
- package.json
- src/containers/Article.js
[[會員制] 閱讀文章篇數、閱讀時間串接](https://app.asana.com/0/1203699264568808/1206008027632075/f) defects
> fix: clear timer if visibility change

- CHANGELOG.md
- package.json
- src/containers/Article.js
[[會員制] 閱讀文章篇數、閱讀時間串接](https://app.asana.com/0/1203699264568808/1206008027632075/f) defects
> fix: set start reading time to now after active

- CHANGELOG.md
- package.json
- src/containers/Article.js
set isActive to false after visibility change to hidden
> fix: set isActive to false after visibility change to hidden

- CHANGELOG.md
- package.json
- src/components/member-page/menu-list.js
- src/components/member-page/mobile-page/mobile-menu-list.js
- src/constants/membership-menu-old.js
- src/constants/membership-menu.js
- src/constants/menu-list-type.js
- src/routes-old.js
[[會員制] 我的閱讀 - 會員頁](https://app.asana.com/0/1203699264568808/1206157706155678/f)
- route path should be updated to use `constants/routes` data after dependency PR merged
https://github.com/twreporter/twreporter-npm-packages/pull/485
> fix: add my-reading entry on member page with feature toggle

- CHANGELOG.md
- package.json
- src/components/my-reading/saved-bookmarks.js
[[會員制] 我的閱讀 - 收藏頁](https://app.asana.com/0/1203699264568808/1206168671896409/f) defects
> fix: show loading and refresh page if no bookmarks

- src/containers/Latest.js
hide bookmark for defects in [[會員制] 我的閱讀 - 最新頁新增收藏功能](https://app.asana.com/0/1203699264568808/1206201445527861/f)
These defects would be resolved in this sprint thus not implement feature toggle for it.
N/A
> chore: hide bookmark on latest before bug resolved

- CHANGELOG.md
- package.json
- src/containers/Article.js
timer won't stop if tab been hidden before componentDidMount
> fix: check visibility at componentDidMount

- CHANGELOG.md
- package.json
- src/containers/Article.js
- src/containers/Latest.js
> chore: test v4.12.6-rc.0 on staging

- CHANGELOG.md
- package.json
> chore: bump version to v4.12.6

- CHANGELOG.md
- package.json
- src/containers/Article.js
> chore: test v.4.12.6 on staging

- src/containers/Category.js
[[維運] 清除「基金會消息」feature toggle](https://app.asana.com/0/1203699264568808/1206398708372261/f)
N/A
> chore: remove `FOUNDATION_CATEGORY_SET` feature toggle

- CHANGELOG.md
- package.json
- src/components/my-reading/empty-box.js
- src/components/my-reading/saved-bookmakrs-section.js
need to show empty page instead of loading spinner
> fix: saved bookmark section loading & text

- CHANGELOG.md
- package.json
- src/components/member-page/email-subscription/Card.js
[[維運] 訂閱電子報頁面：改成三封電子報一個連結](https://app.asana.com/0/1203699264568808/1205990645079185/f) defects
> fix: use P2 for LinkButton

- src/containers/MyReading.js
[[defect] 未登入者需提示跳轉到登入頁
](https://app.asana.com/0/0/1206608856839223/f)
- use same component as `bookmark` page
N/A
> fix: redirect to signin page if not authed when enter myreading page

- src/containers/Member.js
[[defect] sidemenu 點擊「個人專區」少了提示跳轉畫面](https://app.asana.com/0/0/1206626378003735/f)
[[defect] 會員和註冊頁點擊個人專區顯示500畫面](https://app.asana.com/0/0/1206626378003737/f)
N/A
> fix: member page would have js error when ssr

- src/containers/Latest.js
disable bookmark feature before all defects resolved
N/A
> fix: disable bookmark toggle in latest page

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.12.8-rc.2

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.12.8-rc.4

- src/components/member-page/member-data.js
- src/components/member-page/mobile-page/mobile-member-page.js
- src/containers/Member.js
[[維運]會員頁更新：周邊商品的折扣碼訊息](https://app.asana.com/0/1203699264568808/1206388944600937/f)
- the content would be modified in gtm
N/A
> feat: add id for merchandise promo code

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v4.12.8-rc.6

- CHANGELOG.md
- package.json
- src/components/about-us/constants/section-02/carousel-markup.js
- src/components/about-us/constants/section-02/categories.js
- src/components/about-us/constants/section-02/category-ids.js
- src/components/about-us/constants/section-02/headcount-per-page.js
[[維運]更新關於我們-新增部門和成員](https://app.asana.com/0/1203699264568808/1206721263570639/f)
> feat: new category for about us

- CHANGELOG.md
- package.json
> chore: bump version to v4.12.9-rc.1

- CHANGELOG.md
- package.json
- yarn.lock
> chore: test v4.12.9-rc.2 on staging

- CHANGELOG.md
- package.json
- src/components/about-us/constants/section-03/awards-name.json
[[維運]更新關於我們-新增部門和成員](https://app.asana.com/0/1203699264568808/1206721263570639/f) spec change
> feat: new aboust us section 03

- CHANGELOG.md
- package.json
- src/components/about-us/constants/section-03/awards-name.json
- yarn.lock
> chore: test v4.12.9-rc.3 on staging

- CHANGELOG.md
- package.json
- src/containers/Article-new.js
- src/routes.js
Refactor the article page into a functional component to see if it improves prevention of reading time errors.
> feat: article page refactor to functional componet

- CHANGELOG.md
- package.json
- src/components/member-page/email-subscription/index.js
[[維運]會員頁-訂閱電子報修正](https://app.asana.com/0/1203699264568808/1206827670326356/f)
> fix: change email subscription badge text

- CHANGELOG.md
- package.json
- src/components/my-reading/reviewing-article-section.js
[[spec change] 更改文字：和我們一起與議題持續對話](https://app.asana.com/0/0/1207095807997121/f)
> fix: change sub title text

- CHANGELOG.md
- package.json
- src/components/member-page/donation/index.js
- src/components/member-page/donation/status-bagde.js
[[會員制]個人贊助紀錄 phase1 串接](https://app.asana.com/0/1203699264568808/1206804089119549/f) defects
> fix: text and badges status

- Makefile
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
N/A
> fix: build fail in node v18

- CHANGELOG.md
- Makefile
- package.json
- src/components/my-reading/reviewing-card.js
- yarn.lock
> chore: test v5.0.0-rc.3 on staging

- CHANGELOG.md
- package.json
- src/containers/Article-new.js
> fix: fetch at mount while cause duplicated related articles

- CHANGELOG.md
- package.json
- src/components/about-us/index.js
[[defect] about-us 的 logo 遺失](https://app.asana.com/0/0/1207320733207639/f)
> fix: add releaseBrach to Footer

- src/client.js
- src/components/about-us/index.js
- src/containers/Article-new.js
- src/containers/Article.js
- src/containers/Author.js
- src/containers/AuthorsList.js
- src/containers/BookmarkList.js
- src/containers/Category.js
- src/containers/Home.js
- src/containers/Latest.js
- src/containers/Member.js
- src/containers/MyReading.js
- src/containers/Photography.js
- src/containers/Tag.js
- src/containers/TopicLandingPage.js
- src/containers/Topics.js
- src/html.js
fix duplicate helmetProvider in ssr which makes helmet content empty when ssr
related to [this issue](https://github.com/staylor/react-helmet-async/issues/80)
N/A
> fix: duplicate helmet provider issue

- CHANGELOG.md
- package.json
- src/containers/Article-new.js
[[defect] 閱讀時間紀錄異常](https://app.asana.com/0/1203699264568808/1207368896798031/f)
> fix: auth issue for reading time

- CHANGELOG.md
- package.json
- src/containers/Article-new.js
> chore: test v5.0.2-rc.0 on staging

- src/components/member-page/menu-list.js
- src/constants/membership-menu.js
- src/containers/Member.js
[[維運] 個人專區-開創者新增分類：特約優惠](https://app.asana.com/0/1203699264568808/1207310529228749/f)
N/A
> feat: add bookshop friend link on member page menu

- CHANGELOG.md
- package.json
- src/components/member-page/donation/download-page.js
- src/components/member-page/donation/index.js
- src/components/my-reading/reviewing-article-section.js
[[defect]重要報導回顧-無資料時應正常顯示empty state](https://app.asana.com/0/1203699264568808/1207367216972411/f)
> fix: set isLoading to false after dispatch

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v5.0.3-rc.4

- src/components/topic/related/related-as-cards.js
[[維運] 專題頁文章列表互動修正](https://app.asana.com/0/1202936421725081/1207450625816824/f)
- https://styled-components.com/docs/faqs#nested-syntax-handling
N/A
> fix: styled component & behavior change on v6

- CHANGELOG.md
- package.json
- yarn.lock
slack msg: https://twreporter.slack.com/archives/C09N6TNN7/p1717123213877979
因為 PR  https://github.com/twreporter/twreporter-npm-packages/pull/548 還等在 code review 的階段，所以 `@twreporter/react-article-components@2.1.1-beta.0` 版本是從 local 端 build 出來，手動上傳至 npmjs 。
目的是想先確定 PR 的修正是否能夠解決問題。
如果可以解決問題，會再走正式流程部署到 staging 和 release branch。
https://github.com/twreporter/twreporter-npm-packages/pull/548
> chore(hotfix): 

- src/components/notify-and-promo/more.js
- src/components/notify-and-promo/notify-banner.js
- src/components/web-push.js
- src/hooks/use-promo.js
fix defects in [[維運] 恢復 web push 功能 ](https://app.asana.com/0/1203699264568808/1207019872025280/f)
N/A
> fix: web push defects

- src/components/notify-and-promo/notify-banner.js
[[spec change] tablet mobile / btn:「前往操作教學」 不要斷行](https://app.asana.com/0/1203699264568808/1207645130063330/f)
N/A
> fix: more button style

- CHANGELOG.md
- package.json
> chore: bump version to v5.0.5

- CHANGELOG.md
- package.json
- src/components/notify-and-promo/notify-banner.js
> chore: test v5.0.5 on staging

- CHANGELOG.md
- src/components/notify-and-promo/more.js
- src/components/notify-and-promo/notify-banner.js
- src/components/web-push.js
- src/hooks/use-promo.js
> chore: sync master

- CHANGELOG.md
- package.json
- src/html.js
> chore: merge master branch into staging branch

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v5.0.7-rc.1

- CHANGELOG.md
- package.json
- src/components/my-reading/article-tracking-card.js
- src/containers/Article-new.js
- yarn.lock
[[會員制] 重要報導追蹤-串接](https://app.asana.com/0/1203699264568808/1207085276870887/f) defects
> fix: open tab while click article-tracking-card

- CHANGELOG.md
- package.json
- src/components/about-us/web-font.js
- src/components/author-page/author-data.js
- src/components/topic/description/render-content.js
- src/containers/Home.js
- src/containers/Search.js
- src/html.js
- yarn.lock
[[defect] 作者頁超連結顯示不正常且無效](https://app.asana.com/0/1202936421725081/1207793339880766/f)
[go-api#742](https://github.com/twreporter/go-api/pull/742)
> fix: render bio with html

- CHANGELOG.md
- package.json
- src/containers/Search.js
Dompurify will cause search page crashed
> fix: remove dompurify for search

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v5.1.3-rc.2

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v5.1.3-rc.3

- CHANGELOG.md
- package.json
- src/components/member-page/donation/table/row-detail.js
[[維運] 移除是否願意公開姓名的資訊](https://app.asana.com/0/1203699264568808/1208187216310459/f)
> fix: hide isAnonymous option

- src/components/Pagination.js
- src/components/Spinner.js
- src/components/Sponsor.js
- src/components/SystemError.js
- src/components/author-page/author-collection.js
- src/components/author-page/author-data.js
- src/components/authors/author-search-box.js
- src/components/authors/authors.js
- src/containers/Author.js
- src/containers/AuthorsList.js
- src/containers/Category.js
- src/containers/Tag.js
[[維運] redux 升級後續 refactor: RTK (twreporter-react) - part 1](https://app.asana.com/0/1203699264568808/1207644241750074/f)
- use `useDispatch` & `useSelector` instead of `Connect`
N/A
> feat: refactor components in Authors, Categories, Tag page to functional component

- CHANGELOG.md
- package.json
- src/components/about-us/constants/section-02/headcount-per-page.js
[[spec change]有三個](https://app.asana.com/0/1203699264568808/1208338689540179/f)
> fix: change editor row count

- CHANGELOG.md
- package.json
- src/components/about-us/constants/section-02/headcount-per-page.js
> chore: test v5.1.6 on staging

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v5.1.7

- CHANGELOG.md
- package.json
- src/components/member-page/donation/table/row-detail.js
- src/components/member-page/donation/table/row.js
[[spec change] 依據狀態，顯示下載收據、修改贊助資料](https://app.asana.com/0/1203699264568808/1208626266384417/f)
[[spec change] 僅2024/8後訂單可下載收據](https://app.asana.com/0/1203699264568808/1208636834686060/f)
also hide `edit donation info` if not paid
N/A
> fix: add hide `download receipt` rules

- CHANGELOG.md
- package.json
fix `CHANGELOG.md` after merge `dev` to `master`
> chore: fix CHANGELOG.md

- src/components/member-page/donation/table/row-detail.js
- src/components/member-page/donation/table/row.js
[[hotfix] 變更為電子收據後，贊助紀錄未正常顯示贊助資訊](https://app.asana.com/0/1203699264568808/1208685009069495/f)
N/A
> fix: add digital receipt info on donation page

- CHANGELOG.md
- package.json
- src/containers/Article.js
> fix: use relatedsSelector

- CHANGELOG.md
- package.json
- src/containers/Article.js
- yarn.lock
> chore: test v5.2.2-rc.5. on staging

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v5.2.2

- CHANGELOG.md
- package.json
- yarn.lock
> chore:  test v5.2.2 on staging

- src/components/member-page/donation/table/row.js
[[電子收據] 單筆收據下載開放至 2024/1](https://app.asana.com/0/1203699264568808/1208721757990712/f)
- use `createSelector` to prevent [this issue](https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization) (first mentioned in #3019 )
N/A
> fix: update download receipt rules & use `createSelector`

- CHANGELOG.md
- package.json
- src/components/member-page/donation/table/row.js
authentication failed problem when downloading receipt
TYPO !!!
N/A
> fix: authentication token undefined

- CHANGELOG.md
- package.json
- src/components/member-page/donation/table/row.js
- yarn.lock
> chore: release v5.2.4 on production

- CHANGELOG.md
- package.json
- yarn.lock
[[hotfix] 後續與迴響改文字「後續/迴響」](https://www.notion.so/twreporter/hotfix-15e8dbdca93280489c43d655f63b658b?pvs=4)
> chore: bump version to v5.2.5-rc.0

- CHANGELOG.md
- package.json
- src/app.js
[[維運] 全站字體修復](https://www.notion.so/twreporter/3245d8e64b504944937681b020105401?pvs=4)
> fix: join font faces with no comma

- CHANGELOG.md
- package.json
- src/app.js
- yarn.lock
> chore: test v5.2.6-rc.0 on staging

- src/components/member-page/donation/index.js
- update download button appear rule
N/A
> fix: yearly receipt download rule

- CHANGELOG.md
- package.json
- src/components/member-page/donation/index.js
[[維運] 贊助紀錄頁說明更新](https://www.notion.so/twreporter/bf93f7a4fd3741b7b8317558d607eb09?pvs=4)
> feat: add download hint for donation page

- CHANGELOG.md
- package.json
- src/components/member-page/donation/index.js
> chore: test v5.2.6-rc.4 on staging

- CHANGELOG.md
- package.json
> chore: bump version to v5.2.6

- CHANGELOG.md
- package.json
- yarn.lock
> chore: bump version to v5.2.10-rc.0

- src/components/member-page/member-data.js
[[維運] 個人專區-贊助者回饋小字](https://www.notion.so/twreporter/1b38dbdca93280f2b55efab7d784f811?pvs=4)
N/A
> fix: hard code promotions on member page

- src/components/member-page/member-data.js
- src/components/member-page/mobile-page/mobile-member-page.js
- src/components/member-page/promotion.js
- src/containers/Member.js
[[defect] 個人專區手機版未顯示贊助資訊](https://www.notion.so/twreporter/defect-1d28dbdca93280619de5cb368ced384b?pvs=4)
N/A
> fix: add `Promotion` for rwd promotions

- CHANGELOG.md
- package.json
- src/components/member-page/exclusive-offers/card.js
- src/components/member-page/exclusive-offers/index.js
will get cors error if url not include 'www'
> fix: add www for url

- CHANGELOG.md
- package.json
- src/constants/membership-menu.js
[[defect] 專屬優惠→專屬回饋](https://www.notion.so/twreporter/defect-20f8dbdca93280029eb2c394ea8143aa?source=copy_link)
> fix: menu list text

- CHANGELOG.md
- package.json
- src/components/member-page/donation/empty-donation.js
- src/components/member-page/donation/index.js
[[defect] 無贊助紀錄者不能正常顯示匯入提示popup](https://www.notion.so/twreporter/defect-popup-2328dbdca932804682c3c460e0f72f84?source=copy_link)
> fix: handle offline donation at empty state

- src/components/about-us/section-03/content.js
[[defect] 資料被截斷無法完整檢視](https://www.notion.so/twreporter/defect-22d8dbdca93280a3b089fdb782a14e0f?source=copy_link)
N/A
> fix: add one more page for SOPA

- .circleci/config.yml
- CHANGELOG.md
- package.json
related to https://github.com/twreporter/narwhale/pull/325
N/A
> chore: fix docker not found when build
