twreporter/twreporter-react

src/containers/Home.js

After image resizing according to window size,
this prevention is not needed anymore
@hcchien

remove scorllTo top after page refresh

---

src/components/TopNews.css

1. make image presented by ratio for smartphone and tablet
2. add css style for tablet
3. ignore description of article when screen size is below 1280(13 inch)
@hcchien

Screen size detect

---

src/components/SystemError.js

@nickhsine 
- use `className` and `style` object
- remove `text-align` because it's already defined in `.nav_logo` css

use className and style object for react component

---

package.json
server/server.js

Compressing the following resources with gzip could reduce their transfer size by 623.6KiB (71% reduction).
* https://www.twreporter.org/main.js could save 476.6KiB (69% reduction).
* https://www.twreporter.org/asset/ScrollMagic.js could save 77.2KiB (76% reduction).
* https://www.twreporter.org/ could save 58.7KiB (83% reduction).
* https://www.twreporter.org/main.css could save 10.5KiB (78% reduction).
* https://www.twreporter.org/asset/reset.css could save 477B (44% reduction).
* https://www.twreporter.org/ga.js could save 91B (24% reduction).
Reference: https://gtmetrix.com/reports/www.twreporter.org/HaOsB6M3

Optimize static resources transfer using gzip compression

---

README.md

Summary:
The `--dev` option leads to 500 error
Related: #77

Remove --dev option from the instruction

---

package.json
src/components/TopNews.js

To resolve 'getDOMNode is deprecated' warning.
On react-slick `0.9.2`. Carousel would autoplay when user unfocus page. So I also hack `visibilitychange` to stop autoplay carousel when page is not focus or visible

Bump react-slick version to support react 0.14

---

.eslintignore
package.json

@nickhsine 
- Due to the rapid code changes, I add `.eslintignore` to ignore the files under heavy development. One could fix style and remove ignored files gradually during development.
- Add `precommit-hook`

run lint before every commit

---

server/server.js
src/components/Daily.js
src/components/DeviceProvider.js
src/components/Features.js
src/components/More.js
src/components/Tags.js
src/components/TopNews.js
src/containers/Home.js
src/index.js

Like ```<Provider store={store} >```,
it use React context to pass store to every children of ```Provider```.
Therefore, we use ```<DeviceProvider device={store.getState().device}>``` to pass device to every component of  ```DeviceProvider```, and then we don't need to pass device as props in every component needed device.
@hcchien

pass device implicitly by React context

---

src/components/Footer.css

Text is too close to the top of the div area. Add padding to it to look better.
Before:
After:

Add padding in open-source-container

---

src/components/NavBar.css
src/components/NavBar.js

Use media query to render MobileNav for tablets & mobile devices, and render DesktopNav under desktop devices.

render different header navbars using css media queries

---

api/constants.js

@hcchien 
Because we have add api layer on the FE server (host:port/api/),
we can not send API request  to ATS layer(www.twreporter.org/api/), there will be a collision.
So FE server should hit the API REST server directly without remapping by ATS.

hit api layer directly, bypass ats

---

package.json

Because right now forever start the node process in the background, it will make the docker container exited.
We change the npm start script, so the docker container won't exit.
@garfieldduck

Make process running in the foreground for docker

---

spec/actions/tags.test.js
spec/reducers/tags.test.js
src/actions/tags.js
src/reducers/article.js
src/reducers/index.js
src/reducers/tags.js

- add tags reducer
- unit test
Tags reducer will not only store the tag objects in ```state.entities``` but also store the fetching situtation in ```state.tags```.
The redux state will be like the following object
```
{
entities: {
'mock-tag-1': {
name: 'mock-tag-1',
id: 'mongodb-id-1'
...
},
...
},
tags: {
'mock-tag-1': {
isFetching: false,
error: null, 
lastUpdated: 1234567890
}, 
...
}
}
```

add Tags reducer

---

spec/actions/article.test.js
spec/actions/articles.test.js
spec/actions/tags.test.js
spec/reducers/tags.test.js
src/actions/article.js
src/actions/articles.js
src/actions/tags.js
src/reducers/tags.js
src/schemas/index.js

- change the schema of tag, use ```id```, rather than ```name``` as ```idAttribute```
- in redux state, the difference demonstrates in the following code
```
// it's a redux state
// state.tags looks like the following before code change
{
entities: {
tags: {
'tag-name-1': {
...
},
'tag-name-2': {
...
}
}
}
tags: {
'tag-name-1': {
isFetching: false,
error: null
},
'tag-name-2': {
...
}
}
}
// after code change it will look like
{
entities: {
tags: {
'tag-id-1': {
...
},
'tag-id-2': {
...
}
}
}
tags: {
'tag-name-1': {
id: 'tag-id-1',
isFetching: false,
error: null
},
'tag-name-2': {
...
}
}
}
```
Loading tagged articles accepts tag names, and fetch tag ids by tag names first before fetching articles.
There will be more error handling for fetching tag ids, like ```dispatch …
```

code refactor

---

src/components/article/InfoBox.js
src/components/article/Paragraph.js

code change because of this [pr](https://github.com/twreporter/keystone/pull/58)
However, link style is not tuned yet.
Will do it after spec is final.
@garfieldduck

Update InfoBox and Paragraph components

---

src/actions/header.js
src/components/article/BottomRelateds.js
src/components/navigation/NavMenu.js
src/components/navigation/NavMenu.scss
src/components/navigation/TopicPopup.js
src/components/navigation/TopicPopup.scss
src/containers/Article.js
src/containers/NavBar.js
src/reducers/header.js

- avoid duplications in display
- show disabled link for the current article in display on the TopicPopup
- hide current article in display in BottomRelated
- avoid showing load more if related items are less than the limit

Refine topic list on the menu and in the bottom of an article

---

src/components/article/Embedded.js

- The root cause is we upgrade to react@15.3.0, here is the CHANGELOG of
React(https://github.com/facebook/react/blob/master/CHANGELOG.md#1530-july-29-2016).
We should use React.PureComponent to replace pure function
@hcchien 
@garfieldduck

Fix Embedded missing.

---

src/components/article/BottomRelateds.js
src/components/article/BottomRelateds.scss
src/constants/index.js

- fix the bug that BottomRelated is not showing properly for some posts
- replaced '採訪' with '文'

Fix the bug that BottomRelated is not showing properly for some posts

---

src/components/article/Body.js
src/components/article/Common.scss

[Reference: Get iframe height and width while editing.](https://github.com/twreporter/keystone/pull/103) 
And then we can use width and height to align the iframe well.
@garfieldduck

Make Embedded align center even if it is too small

---

src/components/article/Image.js

set maxwidth for lazy-loaded images
@nickhsine

set maxwidth for lazy-loaded images

---

src/components/navigation/NavMenu.js
src/components/navigation/NavMenu.scss
src/components/navigation/SearchBox.js

The search box sometimes won't show up on mobile by using ```Link``` of ```react-router``` .
Hence, I replace ```Link``` by ```<a>``` tag.
The topic dots and logo are not in the right place on Safari.
@garfieldduck

Style tuning and bug fix

---

src/components/ArticleList.js
src/components/Daily.js
src/components/FeaturesItem.js
src/components/TopNews.js
src/components/article/BottomRelateds.js
src/components/article/PageNavigation.js
src/components/navigation/Bookmarks.js
src/components/navigation/TopicPopup.js
src/components/shared/LeadingVideo.js
src/components/topic/Cards.js
src/constants/index.js
src/constants/link-prefix.js
src/constants/site-meta.js
src/utils/replace-storage-url-prefix.js

[Add] Add link-prefix.js and site-meta.js for constants
[Update] Use /i/ as prefix for the urls of interactive articles
[Update] Update LeadingVideo.js
[Update] Update src/utils/replace-storage-url-prefix.js
- change /storage/images/ to /images/
- change /storage/videos/ to /videos/
- change /storage/audios/ to /audios/
@garfieldduck

Several Updates

---

package.json

**Temporary solution** 
1. replace forever with pm2 ( to see logs easily)
2. Add --max_old_space_size to increase memory size to 2GB.
The right solution needs more logs,  so currently use this change to monitor the production. 
@garfieldduck

[Update] Update package.json. Replace forever with pm2 and give the --max_old_space_size directive

---

processes.json

**Temporary Solution for preventing server out of memory**
Increase v8 max_old_space_size and restart server by pm2 when memory usage is over the threshold.

[Update] Update processes.json. Add max_memory_restart and increase the --max_old_space_size

---

.babelrc
package.json
webpack/dev.config.js

Which is compatible with react v15.4.x (`react-hot-loader` is used in dev mode)
Ref: [“module not found : Error: Cannot resolve module 'react/lib/ReactMount' ”](http://stackoverflow.com/questions/40652327/module-not-found-error-cannot-resolve-module-react-lib-reactmount)

[Update] Use react-hot-loader v3-beta

---

src/components/Html.js
src/components/article/Audio.js
src/components/article/Image.js
src/components/article/Youtube.js
src/components/navigation/NavBar.js
src/containers/Article.js

**[Problem Description]** <br>
Currently our article page does not support web print (網頁列印), so you may see wrong layout of printing page.
**[Solution]**
1. Change media attribute in the css script tag
2. Use bootstrap print media query
3. Do not show navbar, video, audio, related bottoms and footer component while printing.
@garfieldduck @YuCJ @hanyulo

[Update] Enable print media query and print the article well

---

CHANGELOG.md
src/components/topic/Cards.js

Top description cannot be displayed properly if the content brief has been edited and removed

[Bug] Top description cannot be displayed properly

---

CHANGELOG.md
src/components/article/Annotation.scss
src/components/article/Paragraph.scss
src/themes/common-variables.scss

line-height becomes 1.8 instead of 1.95 when the paragraph contains annotations

Fix inconsistent line-heights of paragraphs containing annotations

---

CHANGELOG.md
package.json
src/routes/index.js
src/server.js

Before this PR, we set `Cache-Control: public, max-age=300` in the response header,
hence, the requests will be cached in the reverse proxy like `cloudflare` and our own `nginx server`.
But after we launch the membership feature,  we can not cache those requests in order to avoid the users from getting the wrong response.
This PR will set `Cache-Control: no-store` in the response header for certain endpoints we don't want to cache, such as `/bookmarks` and `/activate`.
@YuCJ

Set Cache-Control: no-store in those endpoints related to users, such  as /activate and /bookmarks.

---

CHANGELOG.md
package.json
webpack.config.js
yarn.lock

- Turn off css source map with webpack in production
- Bump `twreporter-react-component` version to 2.0.6

Turn off css source map in production and bump twreporter-react-component version to 2.0.6

---

CHANGELOG.md
package.json
src/server.js

[Bug fix] avoid to set response header Cache-Control=public,max-age=300 in certain endpoints like /bookmarks, /activate

 Bump version to 2.4.7

---

CHANGELOG.md
package.json
src/components/article/HeadingAuthor.js
src/components/article/zoom-in-leading-image.js
src/components/shared/License.js
src/containers/App.js
src/containers/Article.js
src/containers/Category.js
src/containers/Tag.js
src/containers/Topics.js
src/helpers/with-layout.js
webpack.config.js
yarn.lock

- Update @twreporter/react-components from 2.1.12 to 3.0.1
- Update @twreporter/registration from 2.1.5 to 3.0.0
- Update @twreporter/redux from 3.0.0 to 4.0.1
For being compatiable with the above dependencies updates.
Do the following things:
1. @twreporter/redux which drop bookmarks related stuffs
2. Import bookmarks related statement (mainly redux actions/reducers) from @twreporter/registration
3. Move Functional Bookmark Icons (add/Remove) back to @twreporter/registration
4. Import bookmark frame from @twreporter/registration rather than react-components
5. Create widget service provider from @twreporter/registration
6. Move auth process from client.js to App.js (server/client side redux store render conflict)
- Enable pagination on tag/category listing page (see this reference …

[Minor Version] Bump version to 2.6.0

---

src/containers/Category.js
src/containers/Tag.js

Listing page will render wrong posts if the posts of the page are not fetched already yet.
Pending re-render before data is fetched.

Update listing container(Category|Tag). Prevent page re-render before data is fetched

---

CHANGELOG.md
package.json
yarn.lock

Add `srcSet` and `sizes` to `img-wrapper.js` so that images of different sizes on index-page will be rendered on resolution demand.

Update @twreporter/react-components package version from 4.0.3 to 4.0.4

---

CHANGELOG.md
package.json
yarn.lock

* Update @twreporter-components version to 4.0.4
- Add `srcSet` and `sizes` to `img-wrapper.js` so that images of different sizes on index-page will be rendered on resolution demand.
* @twreporter/react-components package version from 4.0.3 to 4.0.4
- Replace url prefix of images resources in production state
* Bump version to 2.7.2

Bump version to 2.7.2 (#847)

---

src/components/article/layout/title-row-above.js

This patch adds margin space between channel bar and title on tablet. The new added margin-top value equals to the margin-bottom value of title.

Adds some space between channel bar and title in article page on tablet

---

CHANGELOG.md
package.json
service-worker/service-worker.tmpl
src/client.js
src/components/article/Embedded.js

Since we adopted service worker, `embed.js` of `venngage` works abnormally.
It won't generate the iframe even if we actually render the 
```
// script attributes are given by venngage
<script 
async="true"
src="https://infograph.venngage.com/js/embed/v1/embed.js" 
data-vg-id="KTf59BxqBAA" 
data-title="sexual_assault"
data-w="700"
data-h="525" 
data-multipage="true"
data-f="false">
</script>
```
Because service worker caches the import resources, such as stylesheets and js bundles, window dispatch `load` event early than the time venngage script downloaded and executed. 
And in venngage script(https://infograph.venngage.com/js/embed/v1/embed.js), the script generates the `iframe` by listening to `load` event of `window`.
Therefore,  venngage script won't generate the `iframe`.
We use a …

Bug fix and service worker boilerplate improvement

---

CHANGELOG.md
package.json
src/containers/App.js

In order to change online Database schema, stop web push service for a while.
We will resume the service after backend service fully updated.

Bump to 3.0.3

---

src/components/article/tools/DesktopArticleTools.js

Sorry, just can’t bear seeing this lol
However, this is a quick fix, it must have a better way to fix this.
before:
after:

fix(ui): quick fix for desktop tool position

---

.circleci/config.yml

The latest version of kubectl(v1.11.0) breaks the circle builds.
Before our containers upgrades to v1.11.0, we remain kubectl clients on v1.8.7.
@babygoat

Fix circleci build failing. Install the corresponding kubectl pkg

---

src/components/about-us/section-04/index.js
src/components/about-us/utils/pop-up-panel.js

This patch adds an event listener for the `onResize` event to change window height when the URL bar is collapsed. This situation was found in chrome browser of android devices.

 [Bug]Adjust window height of pop-up-panel dynamically on about-us page

---

src/components/article/Embedded.js
src/components/article/getArticleComponent.js

Fix venngage embedded code was replace when embedded code is updated:
- Save return value of Loadable into closure to prevent creating new Component every time `getComponent` is called
- Update EmbeddedCode to PureComponent to prevent rerender when props not changed

Update React-Loadable and EmbeddedCode

---

src/components/about-us/section-02/content-carousel-list.js

[Update] Use Object.assign to create a new object in order not to modify the original data `groupedMembers`

[Bug] Prevent from changing original data object in section2 on about-us page

---

src/constants/static-file-prefix.js
src/containers/Home.js
src/helpers/with-layout.js

This patch adds static files prefix to pages footer apart from homepage. And uses default theme color as the constant `props` `bgColor`which is passed to Footer component.

[Bug] Fix background color of footer in article pages and remove static file path from props of Footer component

---

src/components/about-us/constants/section-02/categories.js
src/components/about-us/constants/section-02/category-ids.js
src/components/about-us/section-02/content-carousel-list.js
src/components/about-us/section-02/content-paginated-list.js
src/components/about-us/section-02/index.js

This PR consists of two commits as below:
1. Changes the order of departments in section2 of about-us page. 
In this commit, I also uses `categories.js` file to keep the order and removes `lodash/value` since it returns the values of object `groupedMembers` and would lead to unexpected order.
2.  [Bug] Fix bug which causes error when clicking logo on the header of about-us page.
Since React assigns refs back to null when it unmounts. When the component is being unmounted, the refs callback receives `null` as an argument. In our case, that is `(null) => this.memberList(index) = null` . And if we already set `this.memberList` (which is an array contains all of the refs) to null, it would cause the error.

Updates in about-us page

---

src/components/article/Annotation.scss

發現在 FireFox 上 `<abbr>` 展開後小白箭頭有正常倒轉，可是會往下方跑版
原因似乎是 `::after` 的 height 在 FireFox 會被算成奇怪的高度（不確定是不是FireFox的bug）
但對 psudo element 加上 `height: 0;` 就會正常了
p.s. 實測 Chrome/Safari 因為原本的computed style的height就是0，所以改變前後皆正常

fix Annotation Indicator positioning for FireFox

---

CHANGELOG.md
src/client.js

Handle hash link scroll. When url contains hash link like #section_1, browser will
scroll to that anchor(id) properly.

Handle hash link scroll

---

CHANGELOG.md
package.json
src/containers/App.js

- Change the interval time to ask users to confirm whether they want to receive the web push notifications from one day to one week.

Change notify interval

---

src/components/topic/Description.js
src/containers/TopicLandingPage.js
src/helpers/Html.js
src/themes/common-variables.js

This patch aims to fix topic landing page which has been merged in this [PR](https://github.com/twreporter/twreporter-react/pull/1083) and was reverted after testing on staging server.
- Removed the `Body` component which is used in article pages and reused `getArticleComponent` instead
- Fix  components returned in type `blockquote`, `youtube`, `image` in team description, and abnormal "double" underline hyper links in topic description texts
- Fix the typo `linHeightLarge` in `common-variables`

Fix many components in topic landing page after testing on staging

---

src/components/topic/Description.js

This patch fixes images that are not being centered in `topicLandingPage` `teamDescription`

bugfix: Centerized images in teamDescription (topicLandingPage)

---

CHANGELOG.md
package.json
src/client.js

Currently, we pass `history` object as props into`BrowserRouter`.
However, `BrowserRouter` has its own `history` object already.
So, we remove passing `history` prop.
- Remove props `history` from `BrowserRouter`

Remove props `history` from `BrowserRouter`

---

CHANGELOG.md
package.json
src/reducers/index.js

When the data of an author is updated, we have not build the function to synchronize the author data saved in old post records on Algolia.
So the author data in post records that already existed will be outdated.
The temporarily solution is that we do not update authors in entities when fetching articles of an author.

Add a workaround to author data problem

---

src/components/article/layout/layout-maker.js
src/components/article/layout/title-row-above.js
src/components/article/layout/title-row-upon.js
src/containers/Article.js
src/managers/layout-manager.js
src/managers/theme-manager.js

-  Update src/managers/theme-manager.js. Add `article:fullscreen:normal` and `article:fullscreen:dark` theme
- Update src/managers/layout-manager.js. Render different layout for `article:fullscreen:[normal|dark]` theme
- Update src/containers/Article.js
This patch does the following changes
- Stop using `post.theme` to  render article layout.
- Render different article layout according to `post.style`
- Add `isLeadingAssetFullScreen` and `styles` React Props
- Update src/components/article/layout/title-row-[above|upon].js
Change prop `theme` to `styles` and do some design tuning
- Update src/components/article/layout/layout-maker.js.
This patch does the following changes
- Replace `position.title` and `position.header` by `isLeadingAssetFullScreen`
- Render full screen image with a gray …

Article layout adjustment

---

CHANGELOG.md
src/components/article/Embedded.js

[Kanban Flow Card](https://kanbanflow.com/t/3Nk9smUx)
This patch set `embeddedCode` component to be printable by default and provides a method to hide embedded code component on print by detecting the embedded code start with comment as the declaration

Set `embeddedCode` component to be printable by default

---

CHANGELOG.md
package.json
src/containers/app-shell.js

-----  讀者回饋 -------
你好，我是貴網站的讀者，也有每月定期贊助。
想跟你們反映一下一個網站設計不良的地方。網站的右下角第一次進入網頁的時候會出現這個畫面，理論上按下不同意，以後應該不再出現這個畫面，但是過一陣子後他還是會繼續出現，每次都要點選不同意非常惱人，會讓人不想要閱讀網站。請考慮修正這個問題。
-----  讀者回饋 -------
Modify the web push popup notify box according to new design.
The new mockup renders web push popup notify box on top of the `universal-header`, instead of fixing on the right-bottom corner of web page.
https://kanbanflow.com/t/ef4E3EoP

Adjust web push notify popup appearance

---

CHANGELOG.md
src/containers/TopicLandingPage.js

This patch uses `ogImage` rather than `leadingImage` while keeping `leadingImage` as a default value of og image on topic landing page

Bug fix: Use `ogImage` rather than `leadingImage` as og image on topic landing page

---

CHANGELOG.md
webpack.config.js

The purpose of the original commit is to prevent webpack-dev-server to take the node_modules in its dependencies when using yarn link. But it will cause webpack taking wrong package if there are different version of the same packge be installed.

Revert "Resolve modules from the `node_modules` of this repo firstly"

---

CHANGELOG.md
package.json
yarn.lock

- Update dependencies:
- @twreporter/redux@5.0.2
- @twreporter/react-article-components@1.0.3
- Use redux store to cache settings.fontLevel on browser

Bump version to v4.3.2

---

CHANGELOG.md
src/components/Sponsor.js
src/components/about-us/opening/anchors-panel.js
src/components/shared/DonationBox.js
src/components/side-bar/aboutus-page-side-bar.js
src/components/topic/Header.js

KanbanFlow Card: https://kanbanflow.com/t/mkh8MzGM
In the past, we used 貝殼放大's billing service.
Since the service was not under our domain, we couldn't install GA script to track the requests.
However, we own our donation service(https://support.twreporter.org) now; hence, we can track the requests by installing GA script in the donation pages.
By providing `utm_medium`, `utm_source` and `utm_campaign`, the editors can easily analyze the requests.

`ReactGA.OutboundLink` -> `@twreporter/react-components/lib/donation-link-with-utm`

---

src/client.js

This patch disables the service-worker on preview branch so that the
basic authentication could work as expected.

Disable service-worker on preview branch

---

src/components/topic/description/index.js
src/containers/TopicLandingPage.js

Fix bugs in 4.2.2-rc.1:
問題：
1. client side render topic landing page 的話， related posts 出不來
2. topic landing page 沒有 description 的時候，還是會出現白底紅線

Fix topic description and relateds

---

CHANGELOG.md
package.json
yarn.lock

- Fix home spinner displayed logic
- Fix wrong query retrieving with react-router. After this fix, the page being visited will be documented in url as `?page=<number>` for `Tag`, `Topics`, and `Categories`.
- Add query validator to prevent invalid search query page input
- `@twreporter/velocity-react@^1.4.2` -> `velocity-react@^1.4.3`
- `react-transition-group@^1.2.1` -> `^2.0.0`
- `react-router-dom@^4.3.1` -> `^5.1.2`
- Per file imports are deprecated for react-router-dom
- `@twreporter/index-page@^1.0.4` -> `^1.0.5`
- `@twreporter/react-article-components@1.0.24` -> `^1.0.25`
- `@twreporter/react-components@^8.0.1` -> `^8.0.2`
- `@twreporter/universal-header@^2.1.0` -> `^2.1.1`
- 400c6d0e Prevent invalid search query page input
- efccfe95 Fix wrong query retrieving with react-router
- …

Release v4.4.5

---

CHANGELOG.md
Makefile
package.json
src/containers/Article.js
src/containers/Category.js
src/containers/Tag.js

- Fix list isFethcing logic: If there’s only one item in a list, the previous code will regard the container as at `isFetching` status.
- Fix wrong componentDidUpdate arguments: `nextProps` -> `prevProps`
- Remove PM2 in comments

Bug fixes of v4.4.5

---

package.json
yarn.lock

This patch upgrades npm packages listed as below:
- Upgrade @twreporter/core to v1.1.2-rc.1
- Upgrade @twreporter/index-page to v1.0.6-rc.1
- Upgrade @twreporter/react-article-components to v1.0.26-rc.1
- Upgrade @twreporter/react-components to v8.0.3-rc.1
- Upgrade @twreporter/universal-header to v2.1.2-rc.1

Upgrade @twreporter npm packages

---

.circleci/config.yml

This patch maps the next branch to the production namespace of the new
twreporter cluster.

Add next branch config on circleci

---

.circleci/config.yml

This patch fixes `config.yml`: `{CIRCLE_BRANCH}` -> `${CIRCLE_BRANCH}`

Fix circle-ci `config.yml`

---

.circleci/config.yml

This patch fixes the kubeconfig generated by gcloud CLI which does not
inherit from default compute/region config.

Fix kubeconfig missing zone or regional info

---

CHANGELOG.md
package.json
src/containers/TopicLandingPage.js

This patch fixes og-image type error where should be an url string
rather than `predefinedPropTypes.imgObj`

[hotfix] Fix og-image type error on topic landing page

---

.circleci/config.yml

This patch fixes the missing namespace of the GKE deployment in the
release environment.

chore: fix missing namespace

---

src/components/photography/top-news.js

This patch aims to fix the incorrect appearance of category label (e.g.  '國際・兩岸') in `top-news` section.

fix: category name on photography landing page

---

CHANGELOG.md
package.json

This patch update version to v4.4.20-rc.0 since v4.4.20 is not ready
to release yet.

chore: update version to v4.4.20-rc.0

---

src/logger/index.js

`logging-winston.express.makeMiddleware` will send development
environment logs onto GCP Logging system if local workspace has been
authenticated by gcloud.
Hence, we only run `makeMiddleware` in production environment.

fix: prevent dev env from error reorting

---

src/containers/Article.js
src/containers/TopicLandingPage.js

In this patch, we use memoize-one to avoid
re-shallowCloning (fullTopic|fullPost).
It helps to avoid re-rendering article page body
and topic landing page body if end users just click load more related
articles button.

refactor: use memoize-one to avoid re-rendering

---

service-worker/service-worker-generator.js
src/constants/status-code.js
src/express/server.js

Editors report that preview server (keystone-preview.twreporter.org) didn't show the latest content after modifying it in the keystone-editor.
After digging out, I guess the reason is the content is cached by browser.
Therefore, we remove `Cache-Control: public, max-age=300` response header for preview server.

refactor: do not cache response for preview branch and update service worker runtime cache pattern

---

package.json
src/containers/Article.js
src/containers/TopicLandingPage.js
yarn.lock

In memoize function,
we check `prevPost.id === nextPost.id` and
`prevPost.full === nextPost.full`,
if true, memoize will use the cached post object.
However, that condition makes memoize to return the stale post object.
For example, if editor edits the post object, such as changing the post title,
that change won't make the memoize function to return a new post object.
Therefore, Article page will render the stale data.
[refactor: stop using lodash.merge in entities reducer #150
](https://github.com/twreporter/twreporter-npm-packages/pull/150)
The reason why we use `arePostsIdAndFullEqual` and `areTopicsIdAndFullEqual` is
`redux.entities.posts` and `redux.entities.topics` change all the time.
And that change will cause Article page re-render.
In the [above …

fix: render stale data due to wrong memoize function

---

src/data-loaders/category-list-page.js

In our [error reporting system](https://console.cloud.google.com/errors/COTC6tOXo6DYPQ?time=P30D&project=coastal-run-106202), there are lots of errors due to `catId` not existed.
However, that error should not be an error to be reported.
That error should be 404 (NotFound) error, not 500 (Internal server error) error.

fix: handle catId not existed. return 404 not found res

---

package.json
src/data-loaders/author-page.js
yarn.lock

In our error reporting system, we have been getting lots of server errors on author page (see [stackdriver error reporting](https://console.cloud.google.com/errors/CNHgkt_OkYeULg?time=P30D&project=coastal-run-106202)).
The root cause is that some end users requests url like `www.twreporter.org/authors/process064.html` (see [stackdriver logger](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%20resource.labels.cluster_name%3D%22twreporter%22%20resource.labels.namespace_name%3D%22production%22%20resource.labels.container_name%3D%22twreporter-nginx-v2%22%0AinsertId%3D%224nyzyf7ohhriubr1o%22;timeRange=2020-10-21T20:39:00.207Z%2F2020-10-21T20:40:00.207Z?project=coastal-run-106202)).
There is no data for such requests. 
Currently, our system responses 500 …

fix: handle author page 404 error

---

.circleci/config.yml

This patch updates the kustomize installation steps according to
official
guide(https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/).

chore: update kustomize installation

---

.circleci/config.yml

This patch fixes the kustomize installation path which is default to
the current working directory. As the command is required to the
following steps, move it to /usr/local/bin/.

chore: fix kustomize installation path

---

src/components/topic/related/index.js

Use `og_image` as image fallback for related items of topic landing page

feat: use `og_image` as image fallback for topic landing page

---

src/client.js

This patch utilizes `window.loaction.href` instead of
`window.location.pathname` as the path for Google Analytics to include
search strings.

fix: utilize `window.location.href` as the path for GA

---

src/client.js

This patch utilizes the `window.location.href` when sending GA pageview
event on client side.

fix: utilize `window.location.href` when sending pageview

---

src/client.js

This patch counts the pageviews with `window.location.pathname` +
`window.location.search` instead of full pathname `window.location.href`.

fix: count the pageviews with pathname + query parameters

---

src/components/side-bar/index-page-side-bar.js
src/containers/Home.js

- Remove legacy commented styles.
- Replace unused div with React.Fragment.
- Adjust vertical center style in `index-page-side-bar`.
- Remove `overflow: hidden` from `container`.
According to best practice `graceful degradation`, using position `sticky`(for modern browser) + `fixed`(for legacy browser) to fix this styling issue.
Resolves: #1846

fix(homepage): prevent sidebar from overlapping footer

---

CHANGELOG.md
package.json

This patch downgrades version from v4.6.10 to v4.6.10-rc.1 due to
index page incorrect UI behavior on mobile.

chore: downgrade version to v4.6.10-rc.1

---

src/containers/Home.js

- add `overflow: hidden` to index page container to fix slideshow effect
On [staging.twreporter.org](https://staging.twreporter.org), slideshow effect does not work as expected on mobile devices.
The misbehavior can only be reproduced on real mobile devices, not the browser emulator.

fix: fix slideshow effect for mobile devices on index page

---

CHANGELOG.md
package.json

This patch bumps version to v4.6.10 since it hasn't been released yet.

chore(release): bump version to v4.6.10

---

CHANGELOG.md
package.json

This patch bumps version to v4.6.11-rc.0.

chore: bump version to v4.6.11-rc.0

---

src/containers/Author.js

This patch removes the default email(contact@twreporter.org) of authors.
Address the inquiry from the editors.
issue: twreporter-36

refactor: remove the default email of authors

---

src/components/about-us/index.js
src/containers/Article.js
src/containers/Home.js

This patch sends the `gtm.load` event to reset gtm scroll depth as sonn
as the window is ready.

feat: manually send gtm.load event for SPA

---

src/containers/Article.js
src/containers/Home.js

This patch sends the gtm.load event when the content is ready.

fix: send gtm.load event when the content is ready

---

package.json
src/components/Sponsor.js
src/components/about-us/opening/anchors-panel.js
src/components/side-bar/aboutus-page-side-bar.js
src/components/topic/header.js
yarn.lock

Address [twreporter-66 Remove outbound links with utm
tracking](https://twreporter-org.atlassian.net/browse/TWREPORTER-66).
Since we are migrating to GTM, we will remove the legacy utm search
parameters to avoid duplicated trigger for the same metrics.

refactor: remove utm parameters

---

CHANGELOG.md
package.json

This patch bumps version to v4.6.11-rc.4.

chore: bump version to v4.6.11-rc.4

---

src/components/topic/search-box.js

- Add width for input in the search box
Input's width won't be limited by the parent's width In Firefox. So make the input 200px can fix the bug in Firefox.
Resolves: #1871

fix(search-box): give input a specific width to avoid bug in firefox

---

src/html.js

Address [[TWREPORTER-84] Google optimize page speed testing](https://twreporter-org.atlassian.net/browse/TWREPORTER-84)
This diff adds google optimize snippet to html.js.
The snippet is placed on the top of `<head>` as
the install documentation suggests[1].
ref:
[1] https://support.google.com/optimize/answer/6314801?hl=en&ref_topic=6197443

feat: add google optimize snippet

---

src/components/topic/banner/base.js
src/components/topic/related/base.js
src/constants/typography.js

Resolve [TWREPORTER-109](https://twreporter-org.atlassian.net/browse/TWREPORTER-109)
Currently, English text can not display properly on topic landing page
due to the font family issue.
Since this change, font-family is updated to `ff-tisa-web-pro` by default,
which is identical with the font-family setting in article pages.

refactor: update font-family for English text on topic landing page

---

CHANGELOG.md
package.json

This patch bump version to v4.7.2-rc.0 for header 2.0 testing.

chore: bump version to v4.7.2-rc.0

---

CHANGELOG.md
package.json
yarn.lock

- update yarn.lock for [universal-header v2.2.0-rc.4](https://github.com/twreporter/twreporter-react/pull/1928/files)

Release v4.7.2-rc.0 on staging with fix

---

src/components/web-push.js
src/containers/app-shell.js

Address [TWREPORTER-140](https://twreporter-org.atlassian.net/browse/TWREPORTER-140?atlOrigin=eyJpIjoiNDczOGVjOTgxMGEyNDQwZTk4NTMyMTQ4ZTg4NzY0NDMiLCJwIjoiaiJ9)
This change updates z-index for web push component to ensure it can be
clicked when header is in theme transparent.
screenshot:

fix: call to action banner can not be clicked

---

src/components/photography/slider.js

hi, this is 守傑 & it's a minor improvement of the indicator of carousel:
1. add fading animation of indicators.
2. enhance indicator's contrast between active/inactive states.
please give comments or suggestions, thanks!

feat: add animation to indicator of carousel & enhance contrast

---

src/client.js

this patch fix `Uncaught TypeError: Cannot read properties of undefined` in keyston-preview.

fix: add gtm preview environment config

---

src/components/about-us/section-05/timeline.js
src/components/about-us/utils/error-boundary.js
src/containers/app-shell.js

This patch fixes lint error as follows:
- 'children' is missing in props validation
- Expected error to be handled
- 'mq' is defined but never used

fix: fix eslint error

---

src/app.js
src/routes.js

This patch add custom `renderWithProps` key to identify whether component in react router need to inject `releaseBranch` props or not.
ref: [react route doc](https://v5.reactrouter.com/web/api/Route)

feat: add releaseBranch props into route component

---

CHANGELOG.md
package.json

This patch update CHANGELOG.md & package.json to bump version to v4.7.17-rc.2

chore: bump version to v4.7.17-rc.2

---

src/html.js

Address [TWREPORTER-318](https://twreporter-org.atlassian.net/browse/TWREPORTER-318)
https://github.com/twreporter/twreporter-npm-packages/pull/278 is required by this change.
This patch changes font loader to fix white page issue on mobile safari.

fix: change font loader

---

src/html.js

This patch add `viewport-fit` setting in <meta> to support `safe-area-inset-*` css

fix: support safe-area-inset-* css

---

src/components/about-us/constants/section-03/awards-name.json

Address [TWREPORTER-391](https://twreporter-org.atlassian.net/browse/TWREPORTER-391)
Since the award name (SOPA亞洲出版協會) changes in [spreadsheet](https://docs.google.com/spreadsheets/d/16CVkhaSw5sxwjlSt1c0nLzxG7qzEmeO2gCymVsSY6PE/edit?pli=1#gid=1007344551), the award name should be changed too.

docs: update award name in about-us

---

src/html.js

Address [TWREPORTER-423](https://twreporter-org.atlassian.net/browse/TWREPORTER-423)
This change async loads google optimize script to eliminate
render-blocking resources.

refactor: async load google optimize script

---

src/html.js

Address [Reduce unused CSS: google font CSS link](https://app.asana.com/0/0/1202942985879129/f)
Note that https://github.com/twreporter/twreporter-npm-packages/pull/314 is needed by this change.
This patch regresses to adopt adobe font as the third-party web fonts, here is the reasons:
- In previous change, we used google font to replace adobe font to address the render blocking issue which leads to white page appears while scrolling in iOS browsers.
- After a while, we found that the cause of that issue was the subsetting of a specific font 'Noto Sans TC' and we decided to self-host that font on gcs as a whole (without subsetting).
- So we can see adobe font service has nothing to do with this issue.
- This change aims to improve the performance of the website suggested by PageSpeed …

refactor: adopt adobe font as the third-party web fonts

---

.circleci/config.yml

- use new context twreporter-gcp
- rename GOOGLE_PREVIEW_CLUSTER_NAME to K8S_PREVIEW_CLUSTER_NAME in new context

fix: modify circleci config for new context

---

src/containers/Latest.js

This patch fix [[defect] keystone 最新頁顯示的排序與主網站不一致](https://app.asana.com/0/0/1203964075873147/f)

fix: latest tag order

---

src/components/about-us/constants/section-02/categories.js

[[spec change] 將分眾報區塊名稱改為「少年報導者」](https://app.asana.com/0/1202936421725081/1204619216430521/f)
N/A

fix: kids reporter name in about us page

---

package.json
yarn.lock

This commit is upgrade `@twreporter/redux` to `@^7.7.0-rc.3` to fix a bug on the index page.
For more details, see https://github.com/twreporter/twreporter-npm-packages/pull/415
https://github.com/twreporter/twreporter-npm-packages/pull/415

chore: update @twreporter/redux to ^7.7.0-rc.3

---

src/express/server.js

當使用者在首頁（https://staging.twreporter.org ）登入網站後，將登入的 tab 關閉（瀏覽器上沒有報導者網頁的 tab），再另開新的 tab 時，重新輸入首頁網址（https://staging.twreporter.org ），網頁會呈現沒有登入的狀態。
比較詭異的部分是，如果瀏覽器上
- 仍有 tab 開著報導者網頁或是
- 重新整理沒有登入狀態的網頁
上述的問題就不會出現。
因為使用者第一次點到首頁時，首頁的 response header 帶有 `Cache-Control: public, max-age=300`，所以瀏覽器會將首頁的 response cache 在瀏覽器上。
當我們另開 tab 時，瀏覽器不會發 request 到 origin server，而是選用 cache 的版本，然而，cache 的版本是沒有登入狀態的 html，所以網頁無法維持登入狀態。
將 `max-age=300` 改成 `max-age=0`，強制瀏覽器發送 request。
但這個會增加 server loading，所以加上 `s-maxage=300`，讓 cloudflare CDN 還是儲存 cache；
只不過 cloudflare 的 Page Rule 有設定「當 request cookie 帶有 `id_token` 時，會 bypass cache」，
所以當使用者是登入的狀態時，不會拿到 cache。
- 這是一個測試性的 commit，需要上 staging 驗證。

refactor: update response Cache-Control header value

---

src/components/skeleton.js
src/containers/Latest.js

[[維運] 最新頁文章載入換成 load more button](https://app.asana.com/0/1203699264568808/1205754859454994/f)
- add `Skeleton` component for article cards with RWD
- use load more instead of pagination
- remove support of changing page with url search param `page`
N/A

feat: add article card skeleton & use load more in latest

---

CHANGELOG.md
package.json
src/containers/Article.js

The default value of `startReadingTime` being 0 will cause inaccuracies in the calculation of reading time.

fix: replace state and give startReadingTime default Date.now

---

CHANGELOG.md
package.json
src/containers/Article-new.js

Article page canonical tag got empty slug

fix: get slug from post for canonical

---

Makefile
package.json
src/components/about-us/index.js
src/containers/Article-new.js
src/containers/Article.js
src/containers/Author.js
src/containers/AuthorsList.js
src/containers/BookmarkList.js
src/containers/Category.js
src/containers/Home.js
src/containers/Latest.js
src/containers/Member.js
src/containers/MyReading.js
src/containers/Photography.js
src/containers/Tag.js
src/containers/TopicLandingPage.js
src/containers/Topics.js
src/express/middlewares/render-html.js
src/html.js
webpack.config.js
yarn.lock

fix webpack build fail ([log](https://app.circleci.com/pipelines/github/twreporter/twreporter-react/2613/workflows/61978ab1-a8c5-4bda-8f12-56b637b189e3/jobs/3404))
- `webpack-cli` has separated from `webpack` after webpack v4 ([ref](https://webpack.js.org/migrate/4/#cli))
- replace uglify plugin with `optamize.minimize` ([ref](https://v4.webpack.js.org/configuration/optimization/#optimizationminimize))
- replace react-helmet with react-helmet-async ([ref](https://github.com/nfl/react-helmet/issues/669))
N/A

fix: add `webpack-cli` & remove deprecated uglify plugin

---

src/components/membership-promo/index.js

This bug is hard to reproduce.
Currently, we are not so sure what kind of environment will trigger this error.
However, my computer is macOS and its os version is v14.5.
In this situation, when react renders `Banner` promote component, rather than `Popup` component, the DOMExceptionError occurs.
This patch is simply add `<div>` outside `<PromoContext.Provider>` to make sure that react will find a parent node where to replace `Popup` component to `Banner` under.
```
use-promo.js:40 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
at ol (https://www.twreporter.org/dist/vendors~main.c90291763dcd8b950263.chunk.js:83:94681)
at rl (https://www.twreporter.org/dist/vendors~main.c90291763dcd8b950263.chunk.js:83:94385)
at ol …
```

fix: unexpected DOMExceptionError due to rendering promote `Banner`

---

CHANGELOG.md
package.json
src/html.js

資安公司回報，我們網站用了 cdn.polyfill.io 的 javascript polyfill，而該 polyfill 含有惡意 javascript 程式。
相關文章：
1. [請儘速遠離cdn.polyfill.io 之惡意程式碼淺析](https://blog.huli.tw/2024/06/25/stop-using-polyfill-io/)
2. [【資安日報】6月28日，前幾天Polyfill.io供應鏈攻擊事件曝光 ...](https://www.ithome.com.tw/news/163709)
剛剛測試，目前 cdn.polyfill.io 的網址是拿不到 javascript polyfill 的（見下圖）
加上該 polyfill 主要是給很舊的瀏覽器使用，例如 IE 11。
所以我們先移除此 polyfill 的使用，如有使用者回報問題，我們再找適合的 polyfill 來使用。

fix: remove cdn.polyfill.io script for security issue

---

CHANGELOG.md
package.json
src/containers/Article.js

[文章頁｜header 收合/展開效果異常](https://app.asana.com/0/1203699264568808/1208761465986478/f)
from 官網範例
```javascript
function TodoList() {
// ❌ WARNING: this _always_ returns a new reference, so it will _always_ re-render!
const completedTodos = useSelector(state =>
state.todos.map(todo => todo.completed)
)
}
```
[ref](https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization)

fix: use createSelector to avoid rerender
